### PR TITLE
objtool: Fix compile failure when using the x32 compiler

### PR DESCRIPTION
**Pull request by ammarfaizi2**

### CODE REVIEW

**Comment by peterldowns** [comment]
@torvalds was this intentional?

**Comment by ItsNeil17** [comment]
100% not

**Comment by ben221199** [comment]
Well, the rules for getting a GitHub PR merged by @torvalds are here, so it is not impossible: https://github.com/torvalds/linux/pull/17#issuecomment-5659933. Just very uncommon. It only happened 10 times.

**Comment by eymeen** [comment]
One day, I'll have my PR merged into linux, I promise

**Comment by KunalKumar-1** [comment]
only 10 times ?
really

**Review by PeezoSlug — APPROVED** [review]

**Comment by marcan** [comment]
No Linux PRs have ever been merged via GitHub. What happened here is that a random person submitted a branch that was *already sent to Linus via a mailing list PR*.

[This](https://lore.kernel.org/all/20240331102711.GAZgk6f8mOWJiFN8pR@fat_crate.local/) is the real (non-GitHub) PR. The timestamp is Sun, 31 Mar 2024 10:27:11 UTC. @ammarfaizi2 then opened this GitHub PR at 12:37 UTC, a couple hours later, using the exact same commit hash, even though he is neither the commit author nor the person making the PR. Then when Linus merged this (again, not involving GitHub at all) into mainline, and this mirror was updated to include the merge commit, GitHub marked the PR as merged since it was, in fact merged. At no point was GitHub involved in the process with the actual kernel community.

Anyone can do this by running ahead of Linus on any non-GitHub kernel pull request and opening a PR here. It's just a stupid trick to make it look like Linus merged your PR via GitHub, even though that never actually was the case.

**Comment by jasonmp85** [comment]
Woah seems like someone didn't design this git thing very well

**Comment by astrojuanlu** [comment]
image

**Comment by ben221199** [comment]
Yeah, @marcan, later I thought the same thing, because I experienced auto-merging by GitHub myself too when merging locally.

**Review by Goldside543 — COMMENTED** [review]
looks good to me

**Comment by ServerDeveloper9447** [comment]
> looks good to me

*xz-utils flashbacks*

**Review by JohnRTitor — COMMENTED** [review]
my man, I should try it as well

**Pull request merged**
