### PR TITLE
Let's fork linux to our individual repositories.

### PR DESCRIPTION
**Pull request by TYDQSoft**
Since Linus and Greg have been stripped all Russian contributors for politics reason,we reckon that linux is the proprietary possession of the America,Linux Foundation and their leaders,open source operating system is the surface,not the intrinsic quality.The Linux leaders brazenly violate the open source protocol and lead the politics element in open source project which is widely accepted that non-politicial campaign.  
As a consequence,We should promote the division of Linux community due to the leaders' transgression behaviour.I am convinced  of open-source community will naturally functioning without the Linux Foundation and Linux Leaders themselves.I have forked out  according to my repository.

### CODE REVIEW

**Comment by SakuraRK** [comment]
LGTM

**Comment by SALTWOOD** [comment]
LGTM

**Comment by Lumin-exdo** [comment]
Since US politics is finally introduced into Linux project, there is lot of concern about whether Linus will allow backdoors enter this program, like what happened to xz.

**Comment by Adesoji1** [comment]
> Since Linus and Greg have been stripped all Russian contributors for politics reason,we reckon that linux is the proprietary possession of the America,Linux Foundation and their leaders,open source operating system is the surface,not the intrinsic quality.The Linux leaders brazenly violate the open source protocol and lead the politics element in open source project which is widely accepted that non-politicial campaign. As a consequence,We should promote the division of Linux community due to the leaders' transgression behaviour.I am convinced of open-source community will naturally functioning without the Linux Foundation and Linux Leaders themselves.I have forked out according to my repository.

wow this is serious, Let's all work in peace.

**Comment by izmyname** [comment]
Линус, иди нахуй.

**Comment by Hikari16665** [comment]
NEW OPEN-SOURCE LICENSE CREATED
It's **Linus**!!!

**Comment by liangguifeng** [comment]
LGTM

**Comment by xuangeyouneihan** [comment]
Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.

**Comment by SALTWOOD** [comment]
> > LGTM
> 
> LGTM = Linus, Go to 'M*'(some word starting with 'M') Is it?

true dude

**Comment by peerless2012** [comment]
> Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.

[Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.

**Comment by xuangeyouneihan** [comment]
> > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> 
> [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.

But Gitee seems to have too much limits, for examples, repos need to be examined and verified before going public, and users need to sign in to access public repos unless the repo's maintainer applied for anonymous access

**Comment by peerless2012** [comment]
> > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > 
> > 
> > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> 
> But Gitee seems to have too much limits, for examples, repos need to be examined and verified before going public, and users need to sign in to access public repos unless the repo's maintainer applied for anonymous access. We need a platform with less limitations, rather than more limitations.

At least, it will not delete you because of your country, which is so simple but so difficult for GitHub.

**Comment by TYDQSoft** [comment]
> > LGTM
> 
> LGTM = Linus, Go to 'M*'(some word starting with 'M') Is it?

Can I comprehend it as fuck Linus and Greg(Due to TM means fuck in Chinese)?

**Comment by TYDQSoft** [comment]
> > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > 
> > 
> > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> 
> But Gitee seems to have too much limits, for examples, repos need to be examined and verified before going public, and users need to sign in to access public repos unless the repo's maintainer applied for anonymous access. We need a platform with less limitations, rather than more limitations.

Despite many weaknesses comparing gitee with github,it is a only way that China only have gitee,I have not explode any other git website better than gitee if I neglect github.

**Comment by Faris90** [comment]
I know it’s so stupid

**Comment by Faris90** [comment]
@torvalds politics have no place in Linux

**Comment by zxrcs** [comment]
> > > > 好吧，我认为将此存储库分叉到 GitHub 上的新存储库是不安全的。相反，我们应该将其分叉到不受美国控制的平台上。
> > > 
> > > 
> > > 来自中国的 [Gitee](https://gitee.com/) 似乎符合您的意见。因为中国现在反对美国，不会听美国的声音。
> > 
> > 
> > 但 Gitee 似乎有太多的限制，比如 repos 在公开之前需要经过检查和验证，除非 repo 的维护者申请匿名访问，否则用户需要登录才能访问公有 repos。我们需要一个限制更少，而不是限制更多的平台。
> 
> 尽管 gitee 和 github 相比有很多弱点，但这是中国只有 gitee 的唯一方式，如果我忽略了 github，我没有炸掉任何其他比 gitee 更好的 git 网站。



> > > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > > 
> > > 
> > > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> > 
> > 
> > But Gitee seems to have too much limits, for examples, repos need to be examined and verified before going public, and users need to sign in to access public repos unless the repo's maintainer applied for anonymous access. We need a platform with less limitations, rather than more limitations.
> 
> Despite many weaknesses comparing gitee with github,it is a only way that China only have gitee,I have not explode any other git website better than gitee if I neglect github.

You can use Gitea to set up a Git server to host your repository.

**Comment by EnderLight3336** [comment]
> > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > 
> > 
> > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> 
> But Gitee seems to have too much limits, for example~s~, ~repos need to be examined and verified before going public, and~ users need to sign in to access public repos unless the repo's maintainer has requested and received approval for anonymous access. We need a platform with less limitations, rather than more limitations.

you can try to contact to them, I believe them will welcome such a big project and its contributors :)
If you cannot, I can help you, I'm Chinese

**Comment by EnderLight3336** [comment]
Or you can try to build a git server online, for example spigotmc has its own git repo and website, although I dont know how they deploy it

**Comment by xuangeyouneihan** [comment]
> > > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > > 
> > > 
> > > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> > 
> > 
> > But Gitee seems to have too much limits, for example~s~, ~repos need to be examined and verified before going public, and~ users need to sign in to access public repos unless the repo's maintainer has requested and received approval for anonymous access. We need a platform with less limitations, rather than more limitations.
> 
> you can try to contact to them, I believe them will welcome such a big project and its contributors :) If you cannot, I can help you, I'm Chinese

我也是中国人，但我只是一个比较关注IT的吃瓜群众，感觉实在干不了啥，我联系了他们也不一定会听，不好意思。要不大佬你试试？

English translation: I'm also Chinese, but I'm just an outsider who happens to be more interested in IT, so I don't think they'll consider my proposal (migrating Linux fork to Gitee). Maybe you can give a try?

**Comment by Elvisass** [comment]
> > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> 
> [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.

No, Gitee, please dont. Aside from access restrictions, China has strict censorship on any public information, and on Gitee, it reaches ridiculous levels.

A classic joke: JAVA -> J**A
It will directly overwrite your text.

**Comment by peerless2012** [comment]
Move to gitee is just a joke, are you serious? LOF

**Comment by AkemiKami201** [comment]
well, Linux is proprietary possession of the America. This is a joke....
LGTM

**Comment by bocchi810** [comment]
> Or you can try to build a git server online, for example spigotmc has its own git repo and website, although I dont know how they deploy it

So where can we host the git server, China mainland?USA?Hong Kong?Germany?UK?Singapore?

**Comment by SakuraRK** [comment]
> > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > 
> > 
> > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> 
> No, Gitee, please dont. Aside from access restrictions, China has strict censorship on any public information, and on Gitee, it reaches ridiculous levels.
> 
> A classic joke: JAVA -> J**A It will directly overwrite your text.

I believe you're just being paranoid about this.
In the developer community in mainland China, most of this text censorship is only for some political content. And to make sure that the code is not corrupted, there are real people who do a second manual review after the machine review.
The biggest problem at the moment is that these platforms are not directly controlled by the Chinese government, but rather by a coalition of large corporate interests that ...... resembles a Wall Street near-monopoly (e.g. Huawei, who in fact the Chinese developer community doesn't like either. Even though most of them grumble about some of the Internet censorship mechanisms). The classic example is Huawei and a joint venture with the Chinese development community's infamous name call **CSDN**'s gitcode, which has at least 5 stars of project repositories for its massive unauthorized pulling of all sorts of github stuff (including projects like notepad++, which is anathema to the Chinese community). And later only in the front-end detected access to some of the famous projects (such as notepad + + +) and pop-up a fake 404 window.
But in any case, I'm still in favor of branching existing code that “hasn't” been modified by the linux development team to other code hosting services. Maybe we mainland Chinese developers (or computer enthusiasts) and you guys can work together to think of a better way to deal with this?
This is not just a problem for you, it's a problem for almost all Internet communities, but it manifests itself in different ways in different regions, and I have to say that the behavior of the Linux team, when analyzed, is not any different from the damage done to IT professionals in these other regions.
*The above was translated using DeepL. Just because I can't read such a long English content at once . *
***(There should be have some ASCII Sadly Faces)***

**Comment by CuriousCodingCanadian** [comment]
> > > > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > > > 
> > > > 
> > > > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> > > 
> > > 
> > > But Gitee seems to have too much limits, for examples, repos need to be examined and verified before going public, and users need to sign in to access public repos unless the repo's maintainer applied for anonymous access. We need a platform with less limitations, rather than more limitations.
> > 
> > 
> > Despite many weaknesses comparing gitee with github,it is a only way that China only have gitee,I have not explode any other git website better than gitee if I neglect github.
> 
> You can use Gitea to set up a Git server to host your repository.

Gitea has done things like [merging pull requests into the paid version](https://github.com/go-gitea/gitea/pull/24257), and as such Forgejo is a better alternative, especially for this purpose.

**Comment by peerless2012** [comment]
If you just want to save this repo and sync it, [gitee](https://gitee.com/mirrors/Linux) and [gitcode](https://gitcode.com/gh_mirrors/li/linux/overview) already do this, they sync this project everyday.

Tips, these repo just sync this repo as a mirror, not support to issue or pull request,

**Comment by TYDQSoft** [comment]
> If you just want to save this repo and sync it, [gitee](https://gitee.com/mirrors/Linux) and [gitcode](https://gitcode.com/gh_mirrors/li/linux/overview) already do this, they sync this project everyday.
> 
> Tips, these repo just sync this repo as a mirror, not support to issue or pull request,

However,linux repository in gitcode and gitee are too old to chase after the newest linux kernel version.We should update the linux kernel repository in China to newest linux kernel version by ourselves.

**Comment by petricavalry** [comment]
> > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > 
> > 
> > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> 
> But Gitee seems to have too much limits, for example~s~, ~repos need to be examined and verified before going public, and~ users need to sign in to access public repos unless the repo's maintainer has requested and received approval for anonymous access. We need a platform with less limitations, rather than more limitations.

Try [sourcehut](https://sourcehut.org).

**Comment by stevepaesani** [comment]
Good idea.
But not on github or any other US server.

**Comment by stevepaesani** [comment]
And drop the .com, .net,.org and any tld run by a US company. They (the US) shuts down domains of US managed tlds. They did it to Alwaght.com making up some story (lie) like the Americans always do.

**Comment by stevepaesani** [comment]
More developers will work on a kernel not run by the US than one run by them and Torvalds.
Less toxic environment and better chance at compensation directly from users (novel idea) and not US corporations.
Of course there are other kernels also and with more favorable licenses than the gpl.

**Comment by stevepaesani** [comment]
> > > Well, I think it is not safe to fork this repo to a new repo on GitHub. Instead we should fork it to a platform not controlled by the USA.
> > 
> > 
> > [Gitee](https://gitee.com/) from china seems match your opinion. Because china is against USA currently now, and will not listen USA voices.
> 
> No, Gitee, please dont. Aside from access restrictions, China has strict censorship on any public information, and on Gitee, it reaches ridiculous levels.
> 
> A classic joke: JAVA -> J**A It will directly overwrite your text.

China?
Try the USA .
Any talk about the truth of Jews/Israel's invasions and genocides, the 2014coup in Ukraine heck even the USA's own history is censored. In fact the very lands the USA is on is stolen.
"China" he says.
lol

**Comment by MEMZJJY418** [comment]
> > > > 好吧，我认为将此存储库分叉到 GitHub 上的新存储库并不安全。相反，我们应该将其分叉到不受美国控制的平台。
> > > 
> > > 
> > > [来自中国的Gitee](https://gitee.com/)似乎符合你的意见。因为中国现在正在反对美国，不会听美国的声音。
> > 
> > 
> > 但Gitee似乎有太多的限制，例如~s~,~回购协议在上市前需要经过审查和验证，并且~用户需要登录才能访问公共存储库，除非存储库的维护者已请求并获得匿名访问的批准。我们需要一个限制更少的平台，而不是更多的限制。
> 
> 尝试一下[sourcehut](https://sourcehut.org)。

I support your opinion.
We Chinese people need to use VPN software to access Github.

**Comment by ilnarildarovuch** [comment]
Хотел senior'скому коду научиться, а тут бунт
Хрена-се

**Comment by ilnarildarovuch** [comment]
Хотел senior'скому коду научиться, а тут бунт
Хрена-се

**Pull request closed without merging**
