### PR TITLE
PR #1000

### PR DESCRIPTION
**Pull request by jamjellyfish**

### CODE REVIEW

**Comment by jamjellyfish** [comment]
1000 pull requests that will never be merged :)

**Comment by Lumin-exdo** [comment]
What a pity that #1000 wasn't jokes about Linus

**Comment by jamendaw** [comment]
> What a pity that #1000 wasn't jokes about Linus

Gonna change it to that after 'recent events'

**Comment by jamendaw** [comment]
Done

**Comment by jamendaw** [comment]
Done

**Comment by robercik10192** [comment]
Yeah, they are no trusted because they can remove NSA attempts to put backdoor there

**Comment by olssonn** [comment]
> Yeah, they are no trusted because they can remove NSA attempts to put backdoor there

This

**Pull request closed without merging**
