### PR TITLE
Fisrt Commit

### PR DESCRIPTION
**Pull request by vajn**
test

### CODE REVIEW

**Comment by mehmetkose** [comment]
whot?

**Comment by jmarcher** [comment]
It's a shame what some people do just for the sake of "collaborate" to the kernel, and do not even read that this repo is read-only.

**Comment by ShonInDim** [comment]
May you imagine that he just start learning git & guthub from scratch?
yep it's not excuse at all. 
But do not be evil.

**Comment by jmarcher** [comment]
What do people mean with learning GitHub? What is here to learn?

**Comment by AmiyKumar** [comment]
> May you imagine that he just start learning git & guthub from scratch?
> yep it's not excuse at all.
> But do not be evil.

There are many test repos to do that
or he can create his own repo.

**Comment by vajn** [comment]
Sorry, it's a test commit but i forget to close it😂

**Comment by AmiyKumar** [comment]
> Sorry, it's a test commit but i forget to close it

@vajn you could create your own repo.
Linux kernel repo is not for test commits.

**Comment by mehmetkose** [comment]
close the issue bro, what the hell you waiting

**Comment by tuxutku** [comment]
从现有的内核线程中创建一个新的内核线程
 运行新的线程

**Pull request closed without merging**
