### PR TITLE
Update avc.c

### PR DESCRIPTION
**Pull request by siddhartha-sharma**

### CODE REVIEW

**Comment by ecnepsnai** [comment]
Linus does not respond to pull requests on Github.  Read the documentation: https://github.com/torvalds/linux/blob/master/Documentation/SubmittingPatches

**Comment by siddhartha-sharma** [comment]
how do I get the change published? what you have recommended is horrifying to me, as I am limited to the procedure?

**Comment by fernando-rodriguez** [comment]
There's an app for that: http://teacherswithapps.com/50-best-ipad-apps-for-reading-disabilities/

**Comment by siddhartha-sharma** [comment]
@fernando-rodriguez 50 applications?! seriously..

**Comment by marctmiller** [comment]
so serial, sid dart.

**Comment by siddhartha-sharma** [comment]
who'll merge this PR?

**Comment by ecnepsnai** [comment]
Siddhartha, read the documentation if you want people to take you seriously.  The only reason PRs are allowed on this GitHub repo is because GitHub doesn't provide the ability to disable them.  There are rules, follow them or leave.

**Comment by siddhartha-sharma** [comment]
Sorry! I'll read them @ecnepsnai , fernando confused me.. Sorry again, for the pain to the community.

**Pull request closed without merging**
