### PR TITLE
 MAINTAINERS: Remove maintainers whose names start with A, B or L

### PR DESCRIPTION
**Pull request by g4s8**
People with first letter A, B or L in first name are no longer needed as maintainers.

### CODE REVIEW

**Comment by SuperScript-PRC** [comment]
DO add L into the list!!

**Comment by g4s8** [comment]
> DO add L into the list!!

Sure, removed all L-maintainers

**Comment by zby-c** [comment]
People with letters A, B, C, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z in the name are no longer needed as maintainers!

**Comment by Lumin-exdo** [comment]
you spelt maintainers wrong in title

**Comment by SuperScript-PRC** [comment]
> People with letters A, B, C, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z in the name are no longer needed as maintainers!

so they modify their name to non-latin characters like chinese or japanese :(

**Comment by fr0staman** [comment]
Please do not spam under repositories.

while russia is aggressing against Ukraine - russians should get what they deserve.

I fully support Torvalds' position.

**Comment by xeynyty** [comment]
Will maintainers from Israel or Palestine be banned?

**Comment by xeynyty** [comment]
In fact, I share the point of view of Linus Torvalds. We should resume the practice of measuring skulls in order to purge the Maintainer race of those we don't like. And send the rest to Madagascar, if you know what I mean

**Comment by nge7** [comment]
who can aprove which world is free and which not so? do them all these thousands Ukrainians who FORCED to go to army after **human-catchers** got them on streets and push them into battle zone?

**Comment by Puz1kTelepuz1k** [comment]
> > If russia stops, there will be no war. If Ukraine stops, there will be no Ukraine.
> 
> If Ukraine stops, the whole world will help it. If Donbass stops, people will be hanged from the first pillar. **Fact**

If you want an independent opinion on whether people of Donbas were hanged, ask how was life between 2014-2022 the residents of Mariupol who survived, the residents of Kramatorsk, Sloviansk, Pokrovsk, who were ffree to elect pro-Russian politicians to the Verkhovna Rada. In the local governments, everyone spoke Russian, and this is a fact, even today many people speak Russian, and what? They are being killed, harassed, even after a full-scale Russian invasion?

Personally know people who speak russian in west Ukraine and its... no problem for them

**Comment by xeynyty** [comment]
> > > Если Россия остановится, войны не будет. Если Украина остановится, Украины не будет.
> > 
> > 
> > Если Украина остановится, ей поможет весь мир. Если Донбасс остановится, людей повесят на первом же столбе. **Факт**
> 
> Если вы хотите узнать независимое мнение о том, были ли жители Донбасса повешены, спросите, как жили в период с 2014 по 2022 год выжившие жители Мариуполя, Краматорска, Славянска, Покровска, которые могли свободно избирать пророссийских политиков в Верховную Раду. В местных органах власти все говорили по-русски, и это факт, даже сегодня многие люди говорят по-русски, и что? Их убивают, преследуют даже после полномасштабного российского вторжения?
> 
> Лично знаю людей, которые говорят по-русски на западе Украины, и для них это... не проблема

I am from Donetsk myself and I perfectly remember the news on state channels that there were only terrorists in the Donbas, which means that you just need to kill all those who remain there. I remember how a Ukrainian tank that broke through shot a high-rise building for fun. How they laughed at the children who died from the arrival of a shell in the city center. Are you serious?

**Comment by Nyralei** [comment]
LGTM

**Comment by izmyname** [comment]
> The reactions under this post just confirm that russians who support the war have nothing to do in the free world.

Against politics in open source = war supporter?  Big brain logic.

> while russia is aggressing against Ukraine - russians should get what they deserve.

Yeah, blood for blood, collective responsibility - this will make the world better, surely.

**Comment by Artoooooor** [comment]
Please change the title, you are too specific for this project. Now it is called "various compliance requirements".

**Review by SuperScript-PRC — APPROVED** [review]

**Comment by liangguifeng** [comment]
Doesn't the United States have wars? Why didn't the United States remove American citizens from the Linux maintainer status when it was fighting in Iraq and the Middle East?

The original 'open source without borders' was just a joke. This is not the first time that open source projects have discriminated based on race or country. I am just interpreting it from a neutral perspective. You can have prejudiced views on a country or a person, but you cannot do this with open source projects.

**Review by KawaiiZapic — APPROVED** [review]

**Review by MagicManWithLinux — APPROVED** [review]

**Review by cneicy — APPROVED** [review]

**Review by Nyralei — APPROVED** [review]

**Comment by DreamDonghao** [comment]
> 请不要在仓库下发送垃圾邮件。
> 
> 虽然俄罗斯正在侵略乌克兰 - 俄罗斯人应该得到他们应得的。
> 
> 如果俄罗斯停止，就不会有战争。如果乌克兰停止，就没有乌克兰。
> 
> 这篇文章下的反应只是证实了支持战争的俄罗斯人在自由世界无事可做。
> 
> 我完全支持 Torvalds 的立场。

并不是战争对错的问题好吧

**Comment by mochawoof** [comment]
How does that Russian govt paycheck taste?

**Comment by DreamDonghao** [comment]
> How does that Russian govt paycheck taste?
> 
听不懂

**Comment by cneicy** [comment]
> How does that Russian govt paycheck taste?

Why didn’t I see the money Putin transferred to my ICBC account? By the way, if we need to remove Russian contributors, then remove Israeli ones as well🤣👉.
**What we’re doing is opposing the introduction of political issues into the open-source community.** 
If you’re so fond of political correctness, maybe check if someone has secretly removed your prefrontal cortex, because your perspective here is completely illogical.

**Comment by SuperScript-PRC** [comment]
> > How does that Russian govt paycheck taste?
> 
> 听不懂

well cns dont know their idioms

**Review by kortaol — APPROVED** [review]

**Comment by MingRiSol** [comment]
> Please do not spam under repositories.
> 
> while russia is aggressing against Ukraine - russians should get what they deserve.
> 
> If russia stops, there will be no war. If Ukraine stops, there will be no Ukraine.
> 
> The reactions under this post just confirm that russians who support the war have nothing to do in the free world.
> 
> I fully support Torvalds' position.

If Canada joined the the Soviet Union last centry, what will America do?

**Comment by MingRiSol** [comment]
> Please do not spam under repositories.
> 
> while russia is aggressing against Ukraine - russians should get what they deserve.
> 
> If russia stops, there will be no war. If Ukraine stops, there will be no Ukraine.
> 
> The reactions under this post just confirm that russians who support the war have nothing to do in the free world.
> 
> I fully support Torvalds' position.

If Canada joined the the Soviet Union last century, what will America do?

**Comment by mb6ockatf** [comment]
> > Please do not spam under repositories.
> > while russia is aggressing against Ukraine - russians should get what they deserve.
> > If russia stops, there will be no war. If Ukraine stops, there will be no Ukraine.
> > The reactions under this post just confirm that russians who support the war have nothing to do in the free world.
> > I fully support Torvalds' position.
> 
> If Canada joined the the Soviet Union last century, what will America do?

America will collapse anyways

**Review by waltercool — APPROVED** [review]

**Pull request closed without merging**
