### PR TITLE
replaced readme with the text MOTHER Tatyana Kurtukova

### PR DESCRIPTION
**Pull request by gmehdiev**
Added braille font, I think it is extremely inappropriate that Linux does not care about people with low vision

### CODE REVIEW

**Comment by Cody212** [comment]
Bruh😭

**Comment by p-shcherbatykh** [comment]
crazy

**Comment by OTonGitHub** [comment]
Excuse my ignorance but, how will they actually read it though? I don't think blind people print repos into braille paper.

**Comment by ASHWIN990** [comment]
🤣

**Comment by a-usr** [comment]
Sorry, but I dont **see** how people would have an easier time recognizing a **pattern of tiny dots** compared to regular letters.

**Comment by samwareing** [comment]
Visually impaired folks can, will and should use their screen reader (narration/braille tool) of choice.

This PR is, in my opinion, very ignorant.

Visually impaired people have better solutions to this universal problem, and this particular solution doesn't actually work.

**Review by nikitaspiridonovjuriba — APPROVED** [review]

**Comment by OTonGitHub** [comment]
Ain't no way

**Review by a-usr — CHANGES_REQUESTED** [review]
You are missing a `⠉` somewhere

**Comment by ApplePieCodes** [comment]
> Visually impaired folks can, will and should use their screen reader (narration/braille tool) of choice.
> 
> This PR is, in my opinion, very ignorant.
> 
> Visually impaired people have better solutions to this universal problem, and this particular solution doesn't actually work.

ITS A JOKE

**Comment by yusuftogtay** [comment]
lol

**Pull request closed without merging**
