### PR TITLE
Add support for AR5BBU22 [0489:e03c]

### PR DESCRIPTION
**Pull request by reejk**

### CODE REVIEW

**Comment by jakesyl** [comment]
+1

**Comment by JumpLink** [comment]
@Mottie nice idea :)

**Comment by AnielloManganelli** [comment]
Resurrecting this from the dead. Regarding the issue with the description that does not have a line break, someone is pretty brain dead if they can not figure out to use a <p> and give it a fixed size so that it just wraps itself.

**Comment by kulong0105** [comment]
Watching...

**Comment by JackKnightme** [comment]
#### Manual wrapping is a stupid idea, because it is not responsive, and is not portable. 

The application that is viewing the plaintext is what should be formatting it. If you need to delineate wrapping and non wrapping text, you *should be using delineators* for this that your editor or viewer or terminal can interpret. 

In the modern world of responsiveness and portability, stored text should *never* have line breaks or formatting added to it.

**This is why Markdown was invented**.

Strictly enforcing word-wrap, etc, probably makes sense if you use a terminal for most of your work. If you want to use that same text for the web, or anything other than a proper terminal, you *need* format-less text.

**Comment by rumpelsepp** [comment]
> if you use a terminal for most of your work.

That's the case :smiling_imp:

**Comment by JackKnightme** [comment]
>>if you use a terminal for most of your work.

>That's the case :smiling_imp:

Yes, but the issue was with github's way of doing things. Not everyone uses the terminal exclusively, and with github's model a web centric setup is necessary. This means there are two essential viewpoints to consider, and that neither is inherently moronic. ^_^

**Comment by lightshire** [comment]
Im a bitchass dog. Woof Woof!

**Comment by marctmiller** [comment]
where's esr when ya need him¿

**Comment by nkeck720** [comment]
Guys, remember that GitHub was built with both beginners and advanced programmers like Linus in mind. The interface may seem crappy to an advanced programmer but it needs to be beginner friendly, and since these people may have little or no experience with Git, they made the interface the way it is. I can understand where Linus is coming from, being a developer of Git and also working on the Linux Kernel (which has strict standars just btw), but the goals of GitHub (Being beginner friendly and general purpose) and Linus (creating and maintaining an OS kernel with strict standards on pulls and pushes, with official commit messages) are different. GitHub just isn't suited to the stricter standards behind development of a kernel. I think Linus may be a tad unreasonable for not accepting PR's just because there are beginners to Git on this site making requests who are amazing programmers, but are making them via GitHub because that is the only interface they are used to. That is all.

**Comment by squeedee** [comment]
I don't expect to change @torvalds opinion on this matter but perhaps I can help those who are swayed by his delivery here. 

It's perfectly fine for him to state expectations in his repository. Of course it is. 

The line where he steps into ridicule is not helpful. He can, if he so chooses, to state his requirements (once also, i'm sure there's a contributor's guide someplace) and stop completely short of calling someone a moron. 

It *is* far more effective to stop short of ridicule. 

This is *not* the victim philosophy.

Sugarcoating is at the other end of a continuum from ridicule. In the middle is stated facts and/or requirements. No one deserves ridicule. Not even @torvalds. Even if he chooses to do it himself.

**Comment by nkeck720** [comment]
I never said I was sugarcoating, I was simply stating the fact that there are *very* skilled programmers who only know how to use the GitHub web interface and thus are being ignored by Linus. I think that is simply unreasonable. Linus is denying help he very well could have but since they are new to Git and started on GitHub, he won't accept their work.

**Comment by oelmekki** [comment]
@nkeck720 It's a bit hard to imagine that this one who is a great 
programmer, can write drivers without specs or kernel level code and is 
willing to contribute to linux kernel is not able and willing to learn 
how to use git itself extensively to achieve this :)

Also, the linux kernel is probably way past the point where maximizing 
contributors is an issue.

**Comment by conradjones** [comment]
How about a great amazing programmer who isn't prepared to use bash, GCC,
make etc. Should Linus accommodate building the kernel in visual studio?

**Comment by nkeck720** [comment]
I can see where you are coming from. What I am saying is though that there
are people out there who may have never heard of git. When they start using
git, the github interface is what they learn to use instead of the terminal
interface. While they may he new to git, they still know C inside and out.
That is my point, that at one point or another everyone was new to git but
knew at least what they were doing in their programming.

**Comment by nemobis** [comment]
nkeck720, 10/10/2015 18:31:
> everyone was new to git but
> knew at least what they were doing in their programming.

False. I exhibit myself as counterexample: proper usage of git and code 
review tools allowed me to learn coding, from being a total coding n00b.

**Comment by kaber** [comment]
Am 10. Oktober 2015 17:43:36 WESZ, schrieb nemobis <notifications@github.com>:
>nkeck720, 10/10/2015 18:31:
>> everyone was new to git but
>> knew at least what they were doing in their programming.
>
>False. I exhibit myself as counterexample: proper usage of git and code
>
>review tools allowed me to learn coding, from being a total coding
>n00b.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/torvalds/linux/pull/17#issuecomment-147105036

Guys could you take me off this crap please? I'm not the slightest interested and have no idea why I'm CCed at all.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by alias-mac** [comment]
@kaber, you are receiving updates on this because your commit in:
https://github.com/kaber/nf-nat-ipv6/commit/4533703ebde964fb217979d3d533e53ac1430a2d
has (in the commit message) `#17`, so github relates that automatically and therefore you are automatically subscribed to the same thread you referenced (in this case this one).

I complained to github about a very similar issue: I was receiving notifications from things happening on the forked repo that I don't care about, since I'm not maintaining them.

**Comment by Ismael-VC** [comment]
> And when those people with lower standards try to get their commits included in the kernel, **I will ridicule them** and point out how broken their commit messages or pull requests are.

Wow, really!? I respect @torvalds **work**, but I can't see how anybody could respect **him**, I guess that as long as his arrogance and his geniusness are not mutually exclusive, lots of people don't care at all and even idolize him for that. :worried:

**Comment by pixelrebel** [comment]
>...his arrogance...lots of people don't care at all and even idolize him for that.

I, for one, would be honored if Linus took the time to call me a moron.

>why not just point them how broken their commit messages or pull requests are and link them to your standards guide...if you are taking the trouble to answer

Then golden threads like this one wouldn't exist.  :)

**Comment by Ismael-VC** [comment]
> I, for one, would be honored if Linus took the time to call me a moron.

Good for **you**, but the point is that not all the people take insults from **anyone** with *pride* like you and some others may do. 

Insulting over the internet is super easy, insulting back is also super easy. I wonder if he would also be that rude with any of *those people with lower standards that try to get their commits included in the kernel* in person ...at fist range?

So much for a __*benevolent*__ dictator for life... if such a thing exists.

**Comment by mucamaca** [comment]
I am pretty sure that you wouldn't tell him all this in person...

**Comment by leonklingele** [comment]
Can you please stop spamming my inbox with this useless junk. Thank you

**Comment by Ismael-VC** [comment]
Sure, why not? He is just a man like you and me. Are you implying that you would also be OK if he insulted you? And It doesn't mean that I would be disrespecting him. Not all the people like to be disrespectful.

I'm just wondering, because I cannot truly believe that each and everyone he insults just lets him be, either because they idolize him or *fear* him? 

I would expect at least one of them to fight back, that's all.

**Comment by alias-mac** [comment]
@Ismael-VC, I think you are seeing things in the wrong perspective.
It seems to me that you assume wrong things and if you read carefully above, Linus explained that in the first comment. He got upset when other ppl jumped into the thread and said "open an exception", which I must agree, makes **no sense** to open an exception just because it is 3 lines of code...

There are standards that Linux project is following and all of that is well documented already, thus making statements/comments like those are just a waste of Linus and other ppl's time. If the maintainers of the project (and community) already spent their own time to write those standards and to share them with the community (giving it for free), I strongly believe that all we (including n00bs) should do is: RTFM!
I often see n00bs on forums asking things that could clearly be found by researching a little bit more. It is a my time vs your time problem.

Seems like that you did the same mistake and judged the entire thread.
I would probably burst too and would have the same reaction when I read the comment:
https://github.com/torvalds/linux/pull/17#issuecomment-5659884

Don't you think that was being disrespectful? I do :smile: 

@leonklingele, please unsubscribe the thread (it is easier to press that button than it is to make a comment here).

**Comment by nemobis** [comment]
I'm surprised there isn't a link yet, so here it goes: https://mako.cc/writing/hill-free_tools.html

**Comment by Leventesz** [comment]
We are taking steps to help lead devs enforce *good* commit messages. Hope you like this initiative guys! >>> https://goo.gl/bGfFBw

**Comment by RankedFirst** [comment]
LUL

**Comment by vsoch** [comment]
Hey everyone, just want to peek in and say let's be good to one another. The internet is stinky and without ends, but here on this little page? Let's just be friends. 🤗

**Comment by bdsl** [comment]
> Newbi



>  can someone point me to this "nice pull-request generation module" Linus mentions?

https://git-scm.com/docs/git-request-pull

**Comment by xieyuheng** [comment]
hello ^-^/

**Comment by chesse20** [comment]
> hello ^-^/
Welcome to the comments section of Add support for AR5BBU22 [0489:e03c] #17

**Comment by quasitiger** [comment]
I'm alive :P

**Comment by anzz1** [comment]
Shameless self-plug, but googling for "72 column wrapper" only leads to various discussions about the 72 column wrapping, and bunch of PVC foam wrappers for literal columns for construction.

So I made this site which is simply a textbox where you paste (or type) text, and it automatically wraps the contents to 72 columns which you can then copy and paste wherever.

**[72 Columns](https://anzz1.github.io/72columns/)**

**Pull request closed without merging**
