### PR TITLE
Final conclusion to this drama

### PR DESCRIPTION
**Pull request by windows0202**
Regarding recent incident
Putin ≠ Russia
image

Regarding chinese & russian spammers
image
image

### CODE REVIEW

**Comment by FuckLinus** [comment]
@yupeishan 贱畜杂种支持死妈Liuns封杀无辜贡献者 yupeishan 支那贱畜 因为生在支那 一辈子就该被人踩在脚下

@yupeishan 贱畜杂种支持死妈Liuns封杀无辜贡献者
yupeishan 这个逼崽子看法就是 无辜人因为国籍 被连累活该

@yupeishan Fucking piece of shit supports Linus suspend contributer
Sorry polluted here but you followed him, according to his theory, this is the consequence, you should accept this.

https://github.com/torvalds/linux/pull/1010

**Comment by windows0202** [comment]
Remember,
image

**Comment by FuckLinus** [comment]
> Remember, image

This is only a dream, Linus Torvalds destroied the harmony of Open Source and started the war.

@yupeishan Fucking SICK Zhina curry favour flatter supports fucking NAZI Linus Torvalds hurting innocents
@yupeishan 贱畜杂种支持死妈Liuns封杀无辜贡献者
yupeishan 这个逼崽子看法就是 无辜人因为国籍 被连累活该
@yupeishan Fucking piece of shit supports Linus suspend contributer Sorry polluted here but you followed him, according to his theory, this is the consequence, you should accept this.

**Comment by folisa-ic** [comment]
Finland was a major Nazi member during World War II. Linus (the person behind Linux) is a well-known Nazi. Finland shamelessly invaded the Soviet Union during World War II. This is basic history that everyone needs to understand

**Comment by windows0202** [comment]
Please remember that peoples are not part of government

**Comment by YuxuanQin** [comment]
Remember what? I just remember Linus can kick Russian contributors off since of the fucking history and political issues, that you encourage us to forget, between Finland and Russia. 

Retarded.

**Comment by Licshee** [comment]
you did it the wrong way, you should put the US goverment in the pics, which intentionally breaking the FOSS community ever since the very first days

**Pull request closed without merging**
