### PR TITLE
Replace old README with shiny new Markdown-based README

### PR DESCRIPTION
**Pull request by nhubbard**
Fine tuned and tested, this new README is 100% Markdown. It has (some) syntax highlighting, code recognition and more!

### CODE REVIEW

**Comment by 0xAX** [comment]
https://github.com/torvalds/linux/blob/master/Documentation/SubmittingPatches

**Comment by joshumax** [comment]
That's a lovely addition, but alas, Linus doesn't accept pull requests on GitHub for many important reasons... You can always try to submit this as a patch on the LKML, but AFAIK the kernel README isn't already in markdown for _other_ important reasons, so you will most likely get yelled at...good luck with whatever you do, and if the worst happens, you'll always have your own fork!

**Comment by icePrograms** [comment]
Sorry I am a fairly new dev. And I just joined gethub so I was learning what everything does. I'm not sure what I requested but I wasn't trying to edit anything. I'm here only to read code not submit yet.

**Comment by adymitruk** [comment]
Gethub and iPhone

**Comment by nhubbard** [comment]
Hi @joshumax:
I just wanted this on the GitHub clone of the repository, so that it only displays on GitHub.
If that is possible...

**Comment by Parker8283** [comment]
No, Linus just pushes the changes from the (official Linux git repo)[https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/].

**Pull request closed without merging**
