### PR TITLE
Improve README formatting

### PR DESCRIPTION
**Pull request by pierre42100**
I renamed README file as README.md to make Github able to format it and make it more visual.

### CODE REVIEW

**Comment by s3494110** [comment]
Did you really think this was PR worthy? 

P.S. Linus never merges PR's.

**Comment by KamranMackey** [comment]
Submit a patch to the Linux kernel mailing list @pierre42100. They don't accept PRs here.

**Comment by RaminFP** [comment]
@pierre42100 [who to submit your kernel patch](https://www.reliableembeddedsystems.com/2010_10_20/WE-2.1_Berger-paper.pdf)

**Comment by CocoFox** [comment]
I can do this if everyone is cool with it, im a software engineering student and I'm very good at all things regex, but the readme is important

**Comment by vrkansagara** [comment]
:+1:  @pierre42100

**Comment by pierre42100** [comment]
This PR is now outdated...

**Pull request closed without merging**
