### PR TITLE
Update rt2800usb.c

### PR DESCRIPTION
**Pull request by PatrickCoffey**
added support for D-Link DWA-160 rev c1.

### CODE REVIEW

**Comment by ItzLevvie** [comment]
PRs don't get accepted here.

**Comment by PatrickCoffey** [comment]
Where are they accepted?

**Comment by lenovouser** [comment]
https://github.com/torvalds/linux/pull/17#issuecomment-5654674

> I don't do github pull requests.
> github throws away all the relevant information, like having even a
> valid email address for the person asking me to pull. The diffstat is
> also deficient and useless.
> Git comes with a nice pull-request generation module, but github
> instead decided to replace it with their own totally inferior version.
> As a result, I consider github useless for these kinds of things. It's
> fine for *hosting*, but the pull requests and the online commit
> editing, are just pure garbage.
> I've told github people about my concerns, they didn't think they
> mattered, so I gave up. Feel free to make a bugreport to github.
> Linus

 * **[reddit thread](https://www.reddit.com/r/linux/comments/4ltsxe/dont_submit_changes_for_linux_kernel_via_github/)**
 * **[kernel.org documentation on submitting patches](https://www.kernel.org/doc/Documentation/SubmittingPatches)**
 * **[kernelnewbies explanation on submitting patches](http://kernelnewbies.org/FirstKernelPatch)**
 * **[blog post on submitting patches](https://shkspr.mobi/blog/2014/04/submitting-trivial-linux-kernel-patches/)**

**Comment by PatrickCoffey** [comment]
git.kernel.org is blocked by my proxy. Seems silly that i have to clone to my local machine an entire repo just to change one line of code.

thanks for links though.

Can i send an email to somone? can one of you please submit a patch for this issue?

**Comment by raminfp** [comment]
@PatrickCoffey please look this  https://www.youtube.com/watch?v=LLBrBBImJt4

Thanks,

**Comment by PatrickCoffey** [comment]
That's a video of the text I just read? It doesn't magically poke a hole in my proxy

**Comment by PatrickCoffey** [comment]
ill get some time at the library pc and see if i can get a proper patch submitted. 

cheers for linking docs and vids.

**Pull request closed without merging**
