### PR TITLE
Not Fixed Bugs.

### PR DESCRIPTION
**Pull request by orhan55555**

### CODE REVIEW

**Comment by ItsiAdam** [comment]
Nice fix. Should be pulled.

**Comment by AndreaCioccarelli** [comment]
What's the point of this

**Comment by bigodines** [comment]
"kernel contributor" in his resumé ?

**Comment by legiorange** [comment]
how dare you do that?

**Comment by Trumeet** [comment]
lol 😂😂

**Comment by Mervin1024** [comment]
You are great！

**Comment by gs666** [comment]
WTF？

**Comment by imzf** [comment]
how old are you

**Comment by phariel** [comment]
Are you insane?

**Comment by geminate** [comment]
lol

**Comment by nickdine** [comment]
insane man

**Comment by xpiaoyu** [comment]
Good job, pal!

**Comment by zhangguanzhang** [comment]
强势围观

**Comment by AwadYoo** [comment]
这也太秀了

**Comment by Liam0205** [comment]
Please consider to lock this conversion.

**Comment by orhan55555** [comment]
Fuck me 😭😭.
Enoughhhhh!;!!!

**Comment by BaiBaiRTC** [comment]
It's a tough guy.

**Comment by monkey-soft** [comment]
Are you serious？

**Comment by Ted-Zhang** [comment]
Well done. nice comment. thanks for helping me to understand the Linux code...

**Comment by 75002Benoit** [comment]
i was here

**Comment by tennessine** [comment]
You're on the blacklist.

**Comment by orhan55555** [comment]
> It's a tough guy
You should see me on bed.

**Comment by Germey** [comment]
@orhan55555 牛逼了！

**Comment by cavin2012** [comment]
so new bee ！！！

**Comment by orhan55555** [comment]
> @orhan55555 牛逼了！

I don't understand Japanese 😁

**Comment by AndreaCioccarelli** [comment]
@orhan55555 Neither code, I see

**Comment by Sup0rsonic** [comment]
Brilliant lol

**Comment by MrAMS** [comment]
> > @orhan55555 牛逼了！
> 
> I don't understand Japanese 😁

Chinese, actually...

**Comment by nabilfreeman** [comment]
Orhan you absolute legend

**Comment by kwilliams1987** [comment]
This pull request escalated quickly.

**Comment by bechedire** [comment]
Well, that's one hell of a contribution

**Comment by orhan55555** [comment]
> Orhan you absolute legend. You're gonna go far!!!!
> 
> p.s. 牛逼 means "fn awesome" in Chinese

IDGAF

**Comment by sn99** [comment]
@orhan55555 

vwviyej

**Comment by orhan55555** [comment]
> @orhan55555
> 
> vwviyej
> 
> 2tkw3b

Turkey

**Comment by haodong** [comment]
It has been anonuced to all HRs around the world, and those living in the Three Body system.

**Comment by Mikotochan** [comment]
中出しされることの喜び _!!_

**Comment by deyikong** [comment]
I wanna leave my name here in this PR. 
`//Deyi :)`

**Comment by axegon** [comment]
My new spirit animal! :laughing:

**Comment by axegon** [comment]
What a legend! My new spirit animal! :laughing:

**Comment by thearyong** [comment]
good boy~~

**Comment by sunzhenyucn** [comment]
insane...

**Comment by newdee** [comment]
活久见

**Comment by ScottZhai** [comment]
hhhhhhhhhhh

**Comment by maldiohead** [comment]
真特么硬核玩家

**Comment by alfedsun** [comment]
围观睿智玩家

**Comment by irellik** [comment]
linus-nvidia

**Comment by vertextao** [comment]
You are shining around the world of IT. Good job!

**Comment by munizart** [comment]
LGTM.

**Comment by VonJane** [comment]
闪闪发光啊，围观睿智玩家。

**Comment by Trumeet** [comment]
@newdee @maldiohead @alfedsun @VonJane 
You'd better speak English here because most people here cannot understand Chinese.

**Comment by whberet** [comment]
lol

**Comment by ScaredJin** [comment]
amazing

**Comment by skymei** [comment]
hey guy, good job!

**Comment by annazhong** [comment]
这一波操作666！

> @newdee @maldiohead @alfedsun @VonJane
> You'd better speak English here because most people here cannot understand Chinese.
Nope, most people here speak Chinese ~

**Comment by 782007296** [comment]
what's the point?

**Comment by 782007296** [comment]
???

**Comment by samzhangss** [comment]
???

**Comment by alfedsun** [comment]
> @newdee @maldiohead @alfedsun @VonJane
> You'd better speak English here because most people here cannot understand Chinese.

You are right.But in this case,translation will lose the rhythm.

**Comment by carlosbridi** [comment]
Hey, congrats on your interest in the kernel, I hope you continue to seek knowledge and that in the future, you can contribute more.

**Comment by lhochbaum** [comment]
What a freaking legend.

**Comment by LordApple** [comment]
this should be merged tbh

**Comment by RoccoDev** [comment]
Greetings from Italy 🇮🇹

**Comment by z-zkagami** [comment]
linus torvalds对你使用了必杀技：66666

**Comment by vinkdong** [comment]
image

**Comment by FateForWindows** [comment]
This guy's the most precise floating point I've ever seen!

**Comment by LeoEatle** [comment]
`// Leo :)`

**Comment by HRSkraps** [comment]
Legend. The kid has balls I'll give him that.

**Comment by me11203sci** [comment]
Absolute madlad.

**Comment by PatoCinza** [comment]
Well.. The tests are not breaking, don't see any problems

**Comment by resynth1943** [comment]
```
// Will :D  
```

**Comment by orhanerday** [comment]
Hi everyone,

I’d like to sincerely apologise for this pull request.
Looking back, I realise it was completely unnecessary and not an appropriate way to engage with the Linux kernel project.

At the time (2018), I was still learning how GitHub works and how contributions to large projects like the kernel are supposed to be made. My intent wasn’t to waste anyone’s time or cause a distraction, but I now understand that even small, non-functional changes can create noise and take attention away from important work.

To all the contributors and especially @torvalds, I’m sorry for any inconvenience or disruption this caused. I appreciate the work you all do and have a much greater respect for the proper contribution process now.

Thank you for your understanding,

BR,
Orhan

**Pull request closed without merging**
