### PR TITLE
Ban Israel from Linux kernel too

### PR DESCRIPTION
**Pull request by istiak101**
Ban Israel from Linux kernel too

### CODE REVIEW

**Comment by yeslyko** [comment]
take your meds

**Comment by User8395** [comment]
Shut up. This is why people hate our cause.

**Comment by Artoooooor** [comment]
...due to various compliance requirements.

**Comment by istiak101** [comment]
> Shut up. This is why people hate our cause.

And you shut up. We don't need your soft western Islam where you break all the Islamic rules.

**Comment by User8395** [comment]
> > Shut up. This is why people hate our cause.
> 
> 
> 
> And you shut up. We don't need your soft western Islam where you break all the Islamic rules.

Dude, deleting important files won't get this merged. What do you think Mr. Torvalds will think when he sees this? "Oh those damn pro-Palestinians are trying to ruin the Linux kernel".

You wanna help Palestine? Make dua for them, donate to organizations like WCK. Speak up on Instagram. "oH hUrR bAn IsRaEl FrOm LiNuX" won't do anything. In fact, it will make everything worse.

**Comment by istiak101** [comment]
> Dude, deleting important files won't get this merged. What do you think Mr. Torvalds will think when he sees this? "Oh those damn pro-Palestinians are trying to ruin the Linux kernel".
> 
> You wanna help Palestine? Make dua for them, donate to organizations like WCK. Speak up on Instagram. "oH hUrR bAn IsRaEl FrOm LiNuX" won't do anything. In fact, it will make everything worse.

No point talking to a 13 years old. Lol, you use Instagram? Grow up gen-Z

**Comment by istiak101** [comment]
Also don't talk about what you don't understand. Grow up first. You haven't seen anything yet.

**Comment by User8395** [comment]
> > Dude, deleting important files won't get this merged. What do you think Mr. Torvalds will think when he sees this? "Oh those damn pro-Palestinians are trying to ruin the Linux kernel".
> 
> > 
> 
> > You wanna help Palestine? Make dua for them, donate to organizations like WCK. Speak up on Instagram. "oH hUrR bAn IsRaEl FrOm LiNuX" won't do anything. In fact, it will make everything worse.
> 
> 
> 
> No point talking to a 13 years old. 

My age has nothing to do with this.

> Lol, you use Instagram? Grow up gen-Z

Whether I use instagram or not also has nothing to do with this.

**Comment by User8395** [comment]
> Also don't talk about what you don't understand. 

It seems I understand this situation more than you do.

> Grow up first. You haven't seen anything yet.

Oh I've seen plenty.

**Comment by istiak101** [comment]
> It seems I understand this situation more than you do.

Ok explain then big guy what you understand. And what should we do?

**Comment by User8395** [comment]
> > It seems I understand this situation more than you do.
> 
> 
> 
> Ok explain then big guy what you understand. And what should we do?
> 

Did you not read my earlier comment?

Gotta get a moderator here.

**Comment by istiak101** [comment]
> > > It seems I understand this situation more than you do.
> > 
> > 
> > Ok explain then big guy what you understand. And what should we do?
> 
> Did you not read my earlier comment?
> 
> Gotta get a moderator here.

Lol. Please do. You would see much more chaos here if your wish is fulfilled.

**Comment by User8395** [comment]
> > > > It seems I understand this situation more than you do.
> 
> > > 
> 
> > > 
> 
> > > Ok explain then big guy what you understand. And what should we do?
> 
> > 
> 
> > Did you not read my earlier comment?
> 
> > 
> 
> > Gotta get a moderator here.
> 
> 
> 
> Lol. Please do. You would see much more chaos here if your wish is fulfilled.

It seems _you're_ the 13 year old here. You clearly don't understand that removing Israeli maintainers won't do anything to save the Palestinians. 

Also this PR removes (probably) very important files, so it won't get merged anytime soon.

You're running in circles here. Take this to the mailing list if you actually want to talk to the big guys.

**Comment by istiak101** [comment]
> It seems _you're_ the 13 year old here. You clearly don't understand that removing Israeli maintainers won't do anything to save the Palestinians.

It's not about that. You won't get it Gen-Z.

> Also this PR removes (probably) very important files, so it won't get merged anytime soon.

More Gen-Z BS thought. This is not about merging this PR. Grow up.

> You're running in circles here. Take this to the mailing list if you actually want to talk to the big guys.

Lol. You're dumber than I thought. Do you even think that mailing list is real with these BS?

**Comment by User8395** [comment]
> It's not about that. You won't get it Gen-Z.

If this is about sending a message, this is a pretty shitty message.

> More Gen-Z BS thought. This is not about merging this PR. Grow up.

Don't want to merge the PR? Close it then.

> Lol. You're dumber than I thought. 

Said that dude who thinks Israeli developers are contributing to the genocide

> Do you even think that mailing list is real with these BS?

1. Fix your English
2. Yes. It's real. Go ahead, see what they do when you give this so called PR. They're not gonna do anything on this read-only repository.

**Comment by istiak101** [comment]
> 1. Fix your English

There is nothing to fix.

> 2\. Yes. It's real. Go ahead, see what they do when you give this so called PR. They're not gonna do anything on this read-only repository.

Then stop blabbering about it. I don't find it very useful to talk to a 13 year old.

> Said that dude who thinks Israeli developers are contributing to the genocide

How many Israeli devs do you know? You can't even keep your pajamas tight.

**Comment by User8395** [comment]
This conversation is useless. Nothing good will come out of it and this PR. I will excuse myself. Clearly you are not fit to be in discussions with other people.

I appreciate your concern, but this isn't helping anyone, and never will. Once again, none of the kernel maintainers look at this repo and act on the shit that happens here.

**Comment by istiak101** [comment]
> I appreciate your concern, but this isn't helping anyone, and never will. Once again, none of the kernel maintainers look at this repo and act on the shit that happens here.

Lol

> Gotta get a moderator here.

Lol

Clearly a 13 year old.

**Comment by 0xadeeb** [comment]
> > I appreciate your concern, but this isn't helping anyone, and never will. Once again, none of the kernel maintainers look at this repo and act on the shit that happens here.
> 
> Lol
> 
> > Gotta get a moderator here.
> 
> Lol
> 
> Clearly a 13 year old.

First off 13 year old is not Gen Z moron! And please stop embarrassing Islam and the Palestinians by giving every random person a headache. If you really want to fight for Palestine, go to Gaza and be the real warrior, not a dumb keyboard warrior!

**Comment by User8395** [comment]
> > > I appreciate your concern, but this isn't helping anyone, and never will. Once again, none of the kernel maintainers look at this repo and act on the shit that happens here.
> 
> > 
> 
> > Lol
> 
> > 
> 
> > > Gotta get a moderator here.
> 
> > 
> 
> > Lol
> 
> > 
> 
> > Clearly a 13 year old.
> 
> 
> 
> First off 13 year old is not Gen Z moron! And please stop embarrassing Islam and the Palestinians by giving every random person a headache. If you really want to fight for Palestine, go to Gaza and be the real warrior, not a dumb keyboard warrior!

Ignore this guy. He doesn't want to listen and is stuck in his own delusions.

**Comment by User8395** [comment]
Is Gen Z supposed to be an insult?

**Comment by vmfunc** [comment]
what the fuck

**Comment by vmfunc** [comment]
"This branch has conflicts that must be resolved"

**Comment by User8395** [comment]
> "This branch has conflicts that must be resolved"

OP has mental problems that need to be resolved

**Comment by vmfunc** [comment]
op needs to touch some grass.

**Comment by fantasy0x1** [comment]
> Said that dude who thinks Israeli developers are contributing to the genocide

Yeah, just as Russian developers are in the trenches invading ukraine XD

**Comment by JustForCollege** [comment]
I agree ban these pigfaces.

**Pull request closed without merging**
