### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by yoginth**

### CODE REVIEW

**Comment by impala2** [comment]
Linux is GPLv2 not 3

**Comment by yoginth** [comment]
Ok Thanks, I will change it!




-----Original Message-----

**Comment by ajdlinux** [comment]
@yoginth Please read the message above about github pull requests. Also, the licence is already found in the file `COPYING`, being the traditional filename for copies of the GPL.

**Comment by yoginth** [comment]
Ok, I Will Close this PR.




-----Original Message-----

**Pull request closed without merging**
