### PR TITLE
Fixing maintainers list

### PR DESCRIPTION
**Pull request by stravnik**
Is it correct linus?

### CODE REVIEW

**Review by CoderChang65535 — APPROVED** [review]
LOL

**Review by eatradish — APPROVED** [review]

**Comment by LeaderL-hyper** [comment]
Changes: Removed everything in MAINTAINERS and added `F**k you linus!`

**Review by bowling233 — APPROVED** [review]

**Review by 45gfg9 — APPROVED** [review]

**Comment by denyswsu** [comment]
do you support russian war against Ukraine?

**Review by LordCasser — APPROVED** [review]

**Comment by ThatsEmbarrassing** [comment]
> do you support russian war against Ukraine?

Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.

**Review by SocketSomeone — APPROVED** [review]

**Comment by denyswsu** [comment]
> > do you support russian war against Ukraine?
> 
> Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
It's a WAR not a situation

And surely YOU or OP wont answer with simple yes/no :)

This PR and whole SITUATION is direct result of WAR that russia started against Ukraine

**Comment by ThatsEmbarrassing** [comment]
> > > do you support russian war against Ukraine?
> > 
> > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> It's a WAR not a situation
> 
> And surely YOU or OP wont answer with simple yes/no :)
> 
> This PR and whole SITUATION is direct result of WAR that russia started against Ukraine
> 

I won't, because I don't care about this and this question is not related to the topic. 

The current situation is not about the conflict of Russia and Ukraine or anything else. It is about that the policits should NOT affect open source projects, especially like linux. 

I'd like to not continue talking about any topics related to the policits. And I suggest you do the same.

**Comment by movpushmov** [comment]
> > > do you support russian war against Ukraine?
> > 
> > 
> > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> > It's a WAR not a situation
> 
> And surely YOU or OP wont answer with simple yes/no :)
> 
> This PR and whole SITUATION is direct result of WAR that russia started against Ukraine

почему не на фронте?

**Review by DasSchloss — APPROVED** [review]

**Comment by denyswsu** [comment]
> > > > do you support russian war against Ukraine?
> > > 
> > > 
> > > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> > > It's a WAR not a situation
> > 
> > 
> > And surely YOU or OP wont answer with simple yes/no :)
> > This PR and whole SITUATION is direct result of WAR that russia started against Ukraine
> 
> I won't, because I don't care about this and this question is not related to the topic.
> 
> The current situation is not about the conflict of Russia and Ukraine or anything else. It is about that the policits should NOT affect open source projects, especially like linux.
> 
> I'd like to not continue talking about any topics related to the policits. And I suggest you do the same.

This PR related to "politics" then :)
Death to russian occupiers

**Comment by pashandor789** [comment]
> > > > > do you support russian war against Ukraine?
> > > > 
> > > > 
> > > > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> > > > It's a WAR not a situation
> > > 
> > > 
> > > And surely YOU or OP wont answer with simple yes/no :)
> > > This PR and whole SITUATION is direct result of WAR that russia started against Ukraine
> > 
> > 
> > I won't, because I don't care about this and this question is not related to the topic.
> > The current situation is not about the conflict of Russia and Ukraine or anything else. It is about that the policits should NOT affect open source projects, especially like linux.
> > I'd like to not continue talking about any topics related to the policits. And I suggest you do the same.
> 
> Following your logic this PR related to "politics" as well :) It's so funny that you russians cry about free-speech or any other benefits of democratic countries only when you benefit from it :)) P.S. Death to russian 

> > > > > do you support russian war against Ukraine?
> > > > 
> > > > 
> > > > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> > > > It's a WAR not a situation
> > > 
> > > 
> > > And surely YOU or OP wont answer with simple yes/no :)
> > > This PR and whole SITUATION is direct result of WAR that russia started against Ukraine
> > 
> > 
> > I won't, because I don't care about this and this question is not related to the topic.
> > The current situation is not about the conflict of Russia and Ukraine or anything else. It is about that the policits should NOT affect open source projects, especially like linux.
> > I'd like to not continue talking about any topics related to the policits. And I suggest you do the same.
> 
> Following your logic this PR related to "politics" as well :) It's so funny that you russians cry about free-speech or any other benefits of democratic countries only when you benefit from it :)) P.S. Death to russian 

блин мужик ну ты сам позвонил


> do you support russian war against Ukraine?

приплел знатно, дружище

**Comment by nerfnet** [comment]
> > > > > do you support russian war against Ukraine?
> > > > 
> > > > 
> > > > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> > > > It's a WAR not a situation
> > > 
> > > 
> > > And surely YOU or OP wont answer with simple yes/no :)
> > > This PR and whole SITUATION is direct result of WAR that russia started against Ukraine
> > 
> > 
> > I won't, because I don't care about this and this question is not related to the topic.
> > The current situation is not about the conflict of Russia and Ukraine or anything else. It is about that the policits should NOT affect open source projects, especially like linux.
> > I'd like to not continue talking about any topics related to the policits. And I suggest you do the same.
> 
> Following your logic this PR related to "politics" as well :) It's so funny that you russians cry about free-speech or any other benefits of democratic countries only when you benefit from it :)) P.S. Death to russian occupiers

You sound retarded. Do you lack critical thinking skills?

**Comment by Barugoo** [comment]
> > > > > do you support russian war against Ukraine?
> > > > 
> > > > 
> > > > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> > > > It's a WAR not a situation
> > > 
> > > 
> > > And surely YOU or OP wont answer with simple yes/no :)
> > > This PR and whole SITUATION is direct result of WAR that russia started against Ukraine
> > 
> > 
> > I won't, because I don't care about this and this question is not related to the topic.
> > The current situation is not about the conflict of Russia and Ukraine or anything else. It is about that the policits should NOT affect open source projects, especially like linux.
> > I'd like to not continue talking about any topics related to the policits. And I suggest you do the same.
> 
> Following your logic this PR related to "politics" as well :) It's so funny that you russians cry about free-speech or any other benefits of democratic countries only when you benefit from it :)) P.S. Death to russian occupiers

Is your employer aware of you sending death wishes while having their branding all over your github account?

**Comment by AkemiKami201** [comment]
> do you support russian war against Ukraine?

What does war have to do with this?
don't try to create conflict where there isn't any.

**Comment by demo-pzx** [comment]
> > > do you support russian war against Ukraine?
> > 
> > 
> > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> > It's a WAR not a situation
> 
> And surely YOU or OP wont answer with simple yes/no :)
> 
> This PR and whole SITUATION is direct result of WAR that russia started against Ukraine

Politics is the most foolish, whether it's Putin or Zelensky

**Review by Estrella-Explore — APPROVED** [review]
Linus has put an end to an era of open source

**Comment by NullR3ference** [comment]
> > > do you support russian war against Ukraine?
> > 
> > 
> > Nobody even mentioned the situation between Russia and Ukraine here. Your question is irrelevant and provocative.
> > It's a WAR not a situation
> 
> And surely YOU or OP wont answer with simple yes/no :)
> 
> This PR and whole SITUATION is direct result of WAR that russia started against Ukraine

Your political views should not be taken into account in this case, because you write in Python LOL xD
Keep writting WEB-apps, politic its not yours )

**Comment by lumingzh** [comment]
> do you support russian war against Ukraine?

FUCK the war, but FUCK Nazis first! So, Fuck Ukraine.

**Review by fQwQf — APPROVED** [review]

**Comment by Micro992** [comment]
> do you support russian war against Ukraine?

shut up

**Pull request closed without merging**
