### PR TITLE
Added the Gettysburg Address

### PR DESCRIPTION
**Pull request by vk8a8**

### CODE REVIEW

**Review by Juoelenis — COMMENTED** [review]
This is brainrot, this aint an fix

**Comment by vk8a8** [comment]
abraham lincoln was very much not brainrot. he was the president of the united states

**Review by Juoelenis — COMMENTED** [review]
What in the actual fuck is this, i cant take it anymore theese people think its funny

**Comment by vk8a8** [comment]
its not supposed to be funny he was probably the greatest president weve ever had

**Pull request closed without merging**
