### PR TITLE
Significant kernel performance improvements

### PR DESCRIPTION
**Pull request by lucavinci**
I made huge improvements to the linux kernel by optimizing the code to not even compile at all so the runtime will be very close to O(0). This should make the kernel more usable for most users.

### CODE REVIEW

**Comment by TwistedPrime** [comment]
Very pru

**Comment by shagbag913** [comment]
Can confirm 10x performance improvement

**Comment by maxh65000** [comment]
Also much more power efficient.

**Comment by person4268** [comment]
As much as this increases performance, it sadly removes compatibility for many platforms.

**Pull request closed without merging**
