### PR TITLE
remove MAINTAINERS from countries I don't like

### PR DESCRIPTION
**Pull request by galisma**
Hi, it has come to my attention that certain contributors are being removed for being born in the wrong country. IMHO this isn't enough. To achieve true political correctness we should ban contributors from all countries I personally dislike.
### List of countries to be banned from contributing to the kernel:
<details><summary>Full List</summary>

    Egypt
    Cape Verde
    Kyrgyzstan
    Lithuania
    Maldives
    Tanzania
    Myanmar
    Jamaica
    Malta
    Benin
    Dominican Republic
    Congo
    Solomon Islands
    Cameroon
    Vanuatu
    Eritrea
    New Zealand
    Ghana
    Grenada
    Andorra
    Colombia
    Jordan
    Algeria
    Bulgaria
    Thailand
    Malaysia
    Uganda
    Paraguay
    Finland
    Bahamas
    Zambia
    South Africa
    Timor-Leste
    Belgium
    Bahrain
    Panama
    R̶u̶s̶s̶i̶a (already banned)
    Nigeria
    Haiti
    Australia
    United Arab Emirates
    Barbados
    Holy See
    Spain (the best country)
    Equatorial Guinea
    Czechia
    Palau
    Laos
    Sweden
    Gambia
    Angola
    Senegal
    Kiribati
    Costa Rica
    Liberia
    Canada
    Togo
    Iraq
    Yemen
    Greece
    Democratic Republic of the Congo
    Austria
    Syria
    Gabon
    Cyprus
    Uzbekistan
    Lebanon
    Liechtenstein
    Chad
    Trinidad and Tobago
    Marshall Islands
    Malawi
    Central African Republic
    Israel (for... reasons)
    Madagascar
    Luxembourg
    Brazil
    Romania
    Mali
    North Korea
    Armenia
    Sudan
    Botswana
    Samoa
    Saudi Arabia
    Guinea
    Tonga
    Rwanda
    Netherlands
    Monaco
    Morocco
    Turkey
    Brunei
    Bhutan
    Philippines
    Ecuador
    Nicaragua
    Italy
    Ethiopia
    Afghanistan
    Saint Kitts and Nevis
    India
    Cambodia
    Uruguay
    Qatar
    Serbia
    Saint Lucia
    Libya
    Pakistan
    France (please 🙏🏻)
    Djibouti
    Germany
    Bangladesh
    Micronesia
    Guinea-Bissau
    Kazakhstan
    Hungary
    Poland
    Dominica
    Sao Tome and Principe
    South Korea
    Mauritania
    Guyana
    Eswatini
    Suriname
    Slovakia
    Oman
    Niger
    Singapore
    Denmark
    Belarus
    Bosnia and Herzegovina
    Sierra Leone
    Cuba
    Ireland
    Côte d'Ivoire
    Burundi
    Ukraine
    Papua New Guinea
    Mauritius
    Antigua and Barbuda
    Saint Vincent and the Grenadines
    Fiji
    Portugal
    Somalia
    Kuwait
    Nauru
    Argentina
    Latvia
    Estonia
    Chile
    Moldova
    Turkmenistan
    Georgia
    United States of America
    Nepal
    El Salvador
    Venezuela
    State of Palestine
    North Macedonia
    Tunisia
    Croatia
    Iceland
    Japan
    Slovenia
    Kenya
    Lesotho
    Guatemala
    Switzerland
    Tuvalu
    United Kingdom
    China (你好谷歌翻译)
    San Marino
    Namibia
    Vietnam
    Norway
    Honduras
    Mozambique
    Peru
    Zimbabwe
    Albania
    Belize
    South Sudan
    Burkina Faso
    Mongolia
    Mexico
    Comoros
    Azerbaijan
    Bolivia
    Iran
    Tajikistan
    Montenegro
    Indonesia
    Seychelles
    Sri Lanka
/s
</details>

### CODE REVIEW

**Comment by akuleshov7** [comment]
You have a conflict in this PR, please resolve it and then feel free to merge it. LGTM.

**Review by akuleshov7 — APPROVED** [review]

**Comment by KibaGasteiz** [comment]
The list should be just France.

**Comment by larryw3i** [comment]
I completely extremely exceedingly enormously agree with you.

**Comment by RhinoCoder** [comment]
Its okay. But not enough. I think you should also include some specific creature species to be banned.

**Comment by chunzha1** [comment]
To avoid internal collusion, should people from other countries who have traveled to these countries also be banned?

**Comment by SakuraRK** [comment]
My opinions:
Create a country, just name it Linux, And ONLY this country's citizen to contribution THIS repository.
I want to add Linus to this country's first citizen, And Identity system.

**Comment by istiak101** [comment]
> And Identity system.

His/Her/Linux?

**Review by waltercool — APPROVED** [review]
Approved

**Comment by arthurus36** [comment]
what beef do u have with france man

**Pull request closed without merging**
