### PR TITLE
Fixed spelling error in docs

### PR DESCRIPTION
**Pull request by jakegore**
Fixed errors on the memory management page that were showing on the kernel docs

### CODE REVIEW

**Comment by ilMagnifico** [comment]
The time you used to look up grammatical errors in all the docs, you could have used it for something more profitable.

**Comment by jakegore** [comment]
I was just reading the docs and came across it. I thought I may as well take a couple of seconds to change it.

**Comment by ericm** [comment]
This is a readonly mirror of the kernel if you're not aware.

**Comment by jakegore** [comment]
Ah right, thanks. I haven't done anything like this before 👍 Cheers anyway

**Pull request closed without merging**
