### PR TITLE
Genius MousePen i608x patch fix

### PR DESCRIPTION
**Pull request by Erendis**
okay, now i just sucked myself in front of everyone.
then i'd like to add a few lines required for the device mentioned to work properly. thanks in advance.

### CODE REVIEW

**Comment by bombless** [comment]
https://github.com/torvalds/linux/pull/17#issuecomment-5654674
I like Github PR but clearly not everybody likes it :disappointed:

**Comment by joshumax** [comment]
This issue has already been fixed a while ago, your HID mapping is exactly the same as the one currently in the code-base (See https://www.diffchecker.com/bkdefals), and since there's no additional commits tied to your PR it seems that your fix is simply an unused array (See https://github.com/Erendis/linux/blob/master/drivers/hid/hid-kye.c#L558).

If you are in a bug-fixing mood though, the LKML receives several bug reports each day and I'm sure any patches that correctly fix them would be appreciated.

**Comment by Erendis** [comment]
it has 4 differences, although the second one is only a _2 suffix:

https://github.com/Erendis/linux/blob/master/drivers/hid/hid-kye.c#L193
https://github.com/Erendis/linux/blob/master/drivers/hid/hid-kye.c#L196
https://github.com/Erendis/linux/blob/master/drivers/hid/hid-kye.c#L236
https://github.com/Erendis/linux/blob/master/drivers/hid/hid-kye.c#L240

**Comment by Erendis** [comment]
the line you mentioned is already there indeed, but this block is also needed for the driver to work properly with full drawing area (ymmv)

**Comment by joshumax** [comment]
@Erendis It seems the patch you're trying to send as a PR has already been sent to the LKML (http://www.spinics.net/lists/linux-input/msg31764.html). But I'm still confused, exactly where in your Pull Request is `mousepen_i608x_2_rdesc_fixed` referenced?

**Comment by Erendis** [comment]
yeah, right. cool. thanks!

**Pull request closed without merging**
