### PR TITLE
Fixed Incompatibility with Windows 10

### PR DESCRIPTION
**Pull request by arnavb**
I was trying to compile the Linux kernel source code on Windows, using this command:

```
C:\Users\Arnav> python init/main.c # And all other sources
```

However, I would get an error on the 1st line. Thus, I decided to fix the bugs. Now when I run the code, it works properly. You can thank me now. Now all the Windows 10 users can enjoy the beautiful OS called Linux.

You may think there are indentation issues, but I need them so that MSVC can accept the code.

### CODE REVIEW

**Comment by emiltrotuar** [comment]
lovely

**Comment by arnavb** [comment]
You're welcome.

**Comment by pvtmert** [comment]
this trolling is really went mad lately...

**Comment by iamsubhranil** [comment]
# D
## A
### M
#### N

**Comment by arnavb** [comment]
#### N
### M
## A
# D

**Comment by eamanu** [comment]
Winchoto. 
What is 'choto'?  see this: http://www.diccionarioargentino.com/term/choto

**Comment by linevich** [comment]
Can you do something useful? It's not funny at all.

**Comment by arnavb** [comment]
How do you comment on github?

**Comment by arnavb** [comment]
For those of you who think this is a troll, consider the lives of those unhappy souls who have to run the Linux kernel on Windows 10... but are unable to do so.

**Comment by eamanu** [comment]
@arnavb Oh that is sad. We have to help them

**Comment by NerdOfCode** [comment]
Linux is not an Operating System

**Pull request closed without merging**
