### PR TITLE
Merge pull request #1 from torvalds/master

### PR DESCRIPTION
**Pull request by DeadMetaler**
111

### CODE REVIEW

**Comment by DeadMetaler** [comment]
з

**Comment by jakesyl** [comment]
@torvalds refuses to use github.

**Comment by Boggartfly** [comment]
@DeadMetaler You probably should see [this](https://www.kernel.org/doc/Documentation/SubmittingPatches) if you already haven't! AFAIK your patches will not be accepted as a pul request on Github!

**Comment by parrotgeek1** [comment]
I assume you meant to merge this into your own repo. you got it backwards. please close

**Pull request closed without merging**
