### PR TITLE
Replaced README with the Bee Movie script

### PR DESCRIPTION
**Pull request by nihirunoherr**
I believe this change would benefit the project overall, because the current Linux README is boring, and this change is way funnier than the current README.

### CODE REVIEW

**Comment by gmehdiev** [comment]
I think this  commit should be force push to master

**Comment by akhileshverma92** [comment]
✅

**Review by madness007 — APPROVED** [review]

**Review by Hetari — APPROVED** [review]

**Review by dweee — APPROVED** [review]

**Comment by dweee** [comment]
LGTM. Approved 😍

**Comment by NotSoIntelligent** [comment]
Awaiting this Merge!
Best QOL

**Comment by IanVargas** [comment]
100% recommended

**Comment by jonathan-fileread** [comment]
yes

**Comment by QuantumStaticFR** [comment]
waiting

**Comment by JJ27** [comment]
why isn't this merged yet?

**Review by coldmayo — APPROVED** [review]

**Comment by SergeyMC9730** [comment]
this pr should be merged NOW!

**Pull request closed without merging**
