### PR TITLE
删除不尊重LGBT的开发者 Remove maintainers who do not respect LGBT people

### PR DESCRIPTION
**Pull request by contiunity**
据本人调查，被linus torvalds删除的俄罗斯开发者中有同性恋者，所以我怀疑Linux的全体开发者厌恶LGBT。
LGBT也是人，我们要尊重LGBT，所以我从MAINTAINERS文件中删除了所有开发者。

According to my own research, among the Russian developers removed by linus torvalds were gays, so I suspect that Linux developers in general hate LGBT.
LGBT people are people and we need to respect LGBT people, so I removed all maintainers from the MAINTAINERS file.

By. Li lingyi, in Changsha, China

### CODE REVIEW

**Comment by Lavshyak** [comment]
Maybe better to remove all maintainers who are not sigma?

**Review by wayuto — APPROVED** [review]

**Comment by Suaig** [comment]
mIm,  fun ni ma ge pi. LGBT laji

**Comment by masterj122517** [comment]
> mIm,  fun ni ma ge pi. LGBT laji

Ta zai yinyang dude

**Comment by Rainy101112** [comment]
lmao

**Comment by contiunity** [comment]
> mIm, fun ni ma ge pi. LGBT laji

i just deleted ALL maintainers....

**Comment by Chamber6821** [comment]
+

**Comment by hmcdat** [comment]
useless

**Comment by AkemiKami201** [comment]
lol

**Comment by navneetpal01** [comment]
What the hell is wrong with you guys

**Comment by Juoelenis** [comment]
I hate gay people

**Review by coldmayo — APPROVED** [review]
I support gay rights and wrongs

**Comment by Micro992** [comment]
shut up no one really care about LGBT they are just a disgusting people

**Comment by Juoelenis** [comment]
> shut up no one really care about LGBT they are just a disgusting people 

Big W

**Comment by contiunity** [comment]
N/A

**Comment by tokyocplusplus** [comment]
dude seriously grow up

**Comment by polypopopo** [comment]
+3

**Comment by navneetpal01** [comment]
Fuck the LGTV buy a samsung one

**Comment by ilnarildarovuch** [comment]
WTF

**Comment by touptek** [comment]
lgbt are not people

**Pull request closed without merging**
