### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by slaven-s**
Hi,

I added section "Books" and a link to the Learn Linux in a Month of Lunches written by Steven Ovadia for Manning Publications. We believe this book is a great resource and all members of community will benefit from this information. If you find this inappropriate, please let me know where I can publish it.

### CODE REVIEW

**Comment by shelt** [comment]
[Pull requests are not accepted on Github](https://github.com/torvalds/linux/pull/17#issuecomment-5654674). In any case, this is hardly the type of thing that belongs in the kernel README.

**Comment by marctmiller** [comment]
bull fucking shit

**Comment by LandonPowell** [comment]
Are you trying to shill your book in the kernel readme? Like Shelt said though, Torvalds said "I don't do github pull requests."

**Comment by slaven-s** [comment]
I'm very sorry if I did something wrong. If you can help to add this book somewhere where all members of community will benefit from it, I would be thankful. Thanks.

**Comment by yuxuanchen1997** [comment]
Don't leave commercials on a non-profit open source project! The kernel readme as well.

**Comment by LinkedHK** [comment]
Hi there , whoever maintains the github repo please add on the top of readme info that PR through github isn't accepted and include the reason!

**Comment by f123h456** [comment]
OK
----- Original Message -----

**Comment by zhouyongtao** [comment]
不相关的PR也提交？

**Comment by yuxuanchen1997** [comment]
Okay, here is the thing.

Some one is trying to add commercial on it and we didn't grant.

He/She must be in the wrong place.

**Pull request closed without merging**
