### PR TITLE
Make it way more better

### PR DESCRIPTION
**Pull request by mark-in**

### CODE REVIEW

**Comment by nkeck720** [comment]
If you're gonna make a PR, you had better have some code to improve or a good reason to not have any.  If you want Linus to "Make it way more better," then email him directly about it. Pestering him with empty PRs will help nobody.

**Comment by mark-in** [comment]
It was just a dumb joke by me. Forget it.

**Comment by marctmiller** [comment]
the operating system running the world's servers is a joke?

**Comment by mark-in** [comment]
@marctmiller, Linux is not my project. PR is a joke.

**Comment by nkeck720** [comment]
It makes me so mad when people make PRs like this on code that is, if you haven't noticed, a pretty big deal, and then don't give any way to try and fix it. And then crap like this happens, when people do this as a "joke" but don't ever realize that they are the <strong>entire reason</strong> that people (not just @torvalds) don't want anything to do with GitHub PRs. All I can say is if you're gonna joke about crap like this, grow up and get a life. If you want to help develop, that's one thing, but if you're just gonna spam, then get outta here, you have no place here.

**Comment by marctmiller** [comment]
oh, well in that case, thanks ivan, keep up the good work!

**Comment by mark-in** [comment]
@nkeck720, calm down. There was a typo in the PR title and I haven't intended to comment Linus' work.
btw it had actual improvements but I decided to force-push it and to left it to be a joke. Why can't you just forget about it?

**Comment by marctmiller** [comment]
join the cause or move away from it

**Comment by copyleft7212** [comment]
Quit spamming my inbox!!!!!!
On Nov 24, 2015 8:30 PM, "marc" <notifications@github.com> wrote:
>
> join the cause or move away from it
> On Nov 24, 2015 7:26 PM, "Ivan Markin" <notifications@github.com> wrote:
>
> > @nkeck720 <https://github.com/nkeck720>, calm down. There was a typo in
>
> > the PR title and I haven't intended to comment Linus' work.
> > btw it had actual improvements but I decided to force-push it and to
left

**Comment by nkeck720** [comment]
Sorry. Didn't see replies, my browser didn't refresh.

**Comment by CrazyBonze** [comment]
I don't like computer science jokes, not one bit. Even this one.

**Pull request closed without merging**
