### PR TITLE
Add period for consistency

### PR DESCRIPTION
**Pull request by russellpwirtz**
In a list of items, the other items end in a period. Adding a period to make the list items consistent.

### CODE REVIEW

**Comment by Elizafox** [comment]
Wonderful, but [Linus doesn't accept PR's on github](https://github.com/torvalds/linux/pull/17#issuecomment-5654674).

**Comment by tua79344** [comment]
Please stfu Elizabeth  myers

**Comment by samcn** [comment]
Second that. Stfu Elizabeth. Back in the kitchen

**Comment by mdu4rt3** [comment]
Yes please, you are spamming our inboxes with this garbage.

**Pull request closed without merging**
