### PR TITLE
I don't care about political correctness, I only care about technology itself. Linus in 2014

### PR DESCRIPTION
**Pull request by Fido6**
there is a good video everyone should take a look from Linus in 2014

🤓👇🏼
https://youtu.be/JZ017D_JOPY?t=40

> Linus: I care about technology and I've actually seen projects that took the whole political correctness so far that the project no longer is about the technology.

### CODE REVIEW

**Comment by Mikelunch** [comment]
The world is like a giant boomerang; whatever you throw out will eventually come back and hit you.

so I call the 21st century the `Boomerang Century`

**Review by fQwQf — COMMENTED** [review]
🤣

**Comment by maher1719** [comment]
Since when Linux became political? FOSS is from the people to the people, with no borders! I am very disappointed and ashamed You are changing Linux to be worse than property alternatives!

**Comment by yoyos12138** [comment]
In just a decade, he's changed as a dragon slayer becomes a dragon, or perhaps it's just that the dragon in human skin has simply shed his disguise.

**Comment by WindClan** [comment]
oh no! anyways
its a piece of fucking software, grow up

**Comment by WindClan** [comment]
falsely removing maintainers isn't political. it has nothing to do with "political correctness"
no matter your opinion on the wars going on you can agree that removing maintainers due to their government being bad is a shitty move
every government has done shitty things and the people who live under them shouldn't be effected. its not the fault of a random joe in a country but the government of it

people like you bringing up him talking about being "politically correct" only are making this situation worse, bringing the kernel closer to politics.

**Comment by anewprogramer** [comment]
The past me is not the present me.

**Comment by leegedan** [comment]
so sad

**Comment by izmyname** [comment]
> bringing the kernel closer to politics.

Kernel and the whole open-source, in general, is already a political thing. Always has been, though.

**Comment by WindClan** [comment]
> > bringing the kernel closer to politics.
> 
> Kernel and the whole open-source, in general, is already a political thing. Always has been, though.

not really, or at least not in the same way as what is happening atm
actually the ideal that anybody has the freedom to do anything with software disagrees with not letting people do stuff with your software because of their country of origin

**Comment by MotWnb** [comment]
F*** ~~you Nvidia~~ me

**Pull request closed without merging**
