### PR TITLE
Update acenv.h

### PR DESCRIPTION
**Pull request by gautham-sn**

### CODE REVIEW

**Comment by jmarcher** [comment]
I always find it funny how many people find time to start a PR here and it is just utterly the worst changes ever

**Comment by gautham-sn** [comment]
Hey,

Sorry just did out of curiosity as I was learning git.

**Comment by jmarcher** [comment]
Why send a PR to a public Repo then? just do it on your own repo, it just shows how unprofessional you can be (for future HR people that may look you what you did on GH)

**Comment by michalzarsm** [comment]
Revolutionary change. /j

**Comment by bachtiarpanjaitan** [comment]
Just fork this repo and make changes for your self.

**Comment by tos-follower** [comment]
> Why send a PR to a public Repo then? just do it on your own repo, it just shows how unprofessional you can be (for future HR people that may look you what you did on GH)

@jmarcher i doubt they meant to be unprofessional, they are learning how to use Git and they didn't mean to make a pull request here

**Comment by jmarcher** [comment]
@tos-follower They did not meant it but they still are being unprofessional

**Pull request closed without merging**
