### PR TITLE
MAINTAINERS: Remove some entries due to some reliability requirements.

### PR DESCRIPTION
**Pull request by M1andy**
Follow https://github.com/torvalds/linux/commit/6e90b675cf942e50c70e8394dfb5862975c3b3b2.
Remove some entries due to some reliability requirements. They can come
back in the future if sufficient documentation is provided.

### CODE REVIEW

**Comment by Butterblock233** [comment]
image

**Review by FrostleafChan — APPROVED** [review]
闹麻了

**Comment by ThatsEmbarrassing** [comment]
LGTM!

**Review by ThatsEmbarrassing — APPROVED** [review]

**Review by eatradish — APPROVED** [review]

**Review by SocketSomeone — APPROVED** [review]

**Comment by copi143** [comment]
Please don't use sarcasm or discuss unrelated topics; it's not funny. Most people likely hope the community can return to a politically neutral state.

---

请不要反串或讨论无关内容，这并不好笑。大多数人应该还是希望社区能够恢复到与政治无关的状态的。

**Comment by Butterblock233** [comment]
事已至此，先祝各位节日快乐吧

**Comment by M1andy** [comment]
> Please don't use sarcasm or discuss unrelated topics; it's not funny. Most people likely hope the community can return to a politically neutral state.
> 
> 请不要反串或讨论无关内容，这并不好笑。大多数人应该还是希望社区能够恢复到与政治无关的状态的。

Nearly **everybody** doesn't want to deal with politics in a free or open-source project, but there is no accelerator or brake under my feet. Before the linux foundation or linus revert the commit or give a detailed illstration, these objections remain.

---
没人想在一个开源项目里讨论政治，但是现在控制整个社区言论走向的不是我。在linux基金会和linus给出解释或者撤回那个提交之前，反对意见必然存在。

**Review by Cryolitia — APPROVED** [review]

**Review by Berrysoft — APPROVED** [review]

**Comment by cxw620** [comment]
> Please don't use sarcasm or discuss unrelated topics; it's not funny. Most people likely hope the community can return to a politically neutral state.
> 
> 请不要反串或讨论无关内容，这并不好笑。大多数人应该还是希望社区能够恢复到与政治无关的状态的。

This is simply an anonymous developer attempting to express his dissent.

Moreover, who exactly is imposing political agendas in open-source projects? Linus itself!

**Review by zmshahaha — APPROVED** [review]

**Comment by Elvisass** [comment]
> Please don't use sarcasm or discuss unrelated topics; it's not funny. Most people likely hope the community can return to a politically neutral state.
> 
> 请不要反串或讨论无关内容，这并不好笑。大多数人应该还是希望社区能够恢复到与政治无关的状态的。

If you don't speak up, Linus will keep pushing his politics.

形势由不得你，你不讨论，Linus就会继续引入政治。

**Comment by real-LiHua** [comment]
LGTM

**Review by real-LiHua — APPROVED** [review]

**Comment by humb1t** [comment]
LGTM

**Review by humb1t — APPROVED** [review]

**Comment by AlexHudnev** [comment]
@torvalds  Linus Benedict Torvalds you are a nationalist

**Review by SpaceTimee — APPROVED** [review]

**Review by Seayay — APPROVED** [review]

**Comment by duzhuoshanwai** [comment]
> > Please don't use sarcasm or discuss unrelated topics; it's not funny. Most people likely hope the community can return to a politically neutral state.
> > 请不要反串或讨论无关内容，这并不好笑。大多数人应该还是希望社区能够恢复到与政治无关的状态的。
> 
> Nearly **everybody** doesn't want to deal with politics in a free or open-source project, but there is no accelerator or brake under my feet. Before the linux foundation or linus revert the commit or give a detailed illstration, these objections remain.
> 
> 没人想在一个开源项目里讨论政治，但是现在控制整个社区言论走向的不是我。在linux基金会和linus给出解释或者撤回那个提交之前，反对意见必然存在。

林纳斯现在算不算房间里的大象

**Comment by Licshee** [comment]
Linus just introduced the politics shit into the community by himself, and somebody want everyone else just pretend it didn't happen now!?

**Comment by 4ECA-2120C** [comment]
https://github.com/torvalds/linux/pull/993#issuecomment-2434842411
我超，vv

**Comment by liangguifeng** [comment]
LGTM

**Review by karshPrime — APPROVED** [review]

**Review by CNenfan — APPROVED** [review]

**Review by 1078249029 — APPROVED** [review]

**Pull request closed without merging**
