### PR TITLE
Tiny update mem.c

### PR DESCRIPTION
**Pull request by fantik86**

### CODE REVIEW

**Comment by aiekick** [comment]
why this change ????

**Comment by aleao-sl** [comment]
> why this change ????
Good question... An if block with only one instruction and removed enclosing brackets. It looks like an irrelevant update. does not add benefits in maintainability

**Comment by fantik86** [comment]
> > > why this change ????
> > > Good question... An if block with only one instruction and removed enclosing brackets. It looks like an irrelevant update. does not add benefits in maintainability, but not a bad idea
> 
> i aggree, firt time im comming on this repo, and im so surprised to see many idiot PRs like this one. strange....

I am very sorry, this is my very first pull request...

**Comment by Bug-Reaper** [comment]
@aiekick @fantik86 this repo is a read only mirror of linux. No PRs are ever accepted here.

**Pull request closed without merging**
