### PR TITLE
grammar and spelling for mm/huge_memory.c

### PR DESCRIPTION
**Pull request by mdeguzis**

### CODE REVIEW

**Comment by daxtens** [comment]
Hi Michael,

This looks like a good contribution; if you would like any help getting it
upstream please let me know.

Regards,
Daniel

**Comment by mdeguzis** [comment]
@daxtens , sure, I have never made a contribution yet to the kernel, even this small. Either comment here, or contact me via whatever channel suits you best.

**Comment by mdeguzis** [comment]
I think I got it, configured git send-email, tested with my email first

```
Send this email? ([y]es|[n]o|[q]uit|[a]ll): y
OK. Log says:
Server: smtp.SERVER.com
MAIL FROM:<NAME@SERVER.com>
RCPT TO:<linux-mm@kvack.org>
RCPT TO:<trivial@kernel.org>
RCPT TO:<XXXXXX@XXXXXX.com>
From: FNAME LNAME <XXXXXX@XXXXXX.com>
To: linux-mm@kvack.org
Cc: trivial@kernel.org,
        mdeguzis <NAME@SERVER.com>
Subject: [PATCH] Correct spelling and grammar for notification text
Date: Wed, 17 May 2017 09:38:42 -0400
Message-Id: <20170517133842.5733-1-NAME@SERVER.com>
X-Mailer: git-send-email 2.12.2
```

**Comment by ajdlinux** [comment]
Hey @mdeguzis,

It looks like your git send-email worked: http://marc.info/?l=linux-mm&m=149502833306198&w=2. Woot!

A few things I noticed:

1) You should configure git to use your name in commits - "git config --global user.name "Michael DeGuzis"" should work, I think. Otherwise, git send-email will add "From: professorkaos64 <mdeguzis@gmail.com>" to your patch and the wrong name will end up in the changelog when it's applied.

2) Per step 11 in the submitting patches document, you need a `Signed-off-by: [Name] <[Email]>` line at the end of your commit message. The easiest way is to use `git commit -s` to automatically add one.

3) Your commit title should use the right prefix to identify the subsystem you're touching. There's not really an official standard for this - the best way to figure it out would be to run `git log` on the files you're touching and see what other people have used. In this case, I'd recommend `thp:` (or alternatively `mm:`) based on past usage.

When you resend the patch with `git send-email` use the `-v2 --annotate` options, which will mark it as version 2 of the patch, and open up an editor for you to edit the message before you send it. After the "---" line at the bottom of the commit message, you should add a quick note saying what you fixed between version 1 and version 2.

Feel free to Cc me (andrew.donnellan@au1.ibm.com) and @daxtens (dja@axtens.net) as well.

Welcome to the kernel community. :)

**Comment by mdeguzis** [comment]
I correct my ~/.gitconfig to include my full name. I fixed it from professorkaos64 (my older username) after this.  I'll add `git commit -s` to my notes, thanks!. 

>Your commit title should use the right prefix to identify the subsystem you're touching

Ok, so I did that for the subject, but I missed it in the commit title.  What is the "commit title" here?Would it be the "Merge Tag" line?

```
commit b23afd384801711ab6dbccd259cc14cb09a1dcaf
Merge: 2b6b38b04c2e 6f61dd3aa351
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Tue May 16 13:29:07 2017 -0700

    Merge tag 'pstore-v4.12-rc2' of git://git.kernel.org/pub/scm/linux/kernel/git/kees/linux

    Pull pstore fix from Kees Cook:
     "Fix bad EFI vars iterator usage"

    * tag 'pstore-v4.12-rc2' of git://git.kernel.org/pub/scm/linux/kernel/git/kees/linux:
      efi-pstore: Fix read iter after pstore API refactor
```

>When you resend the patch with git send-email use the -v2 --annotate options, which will mark it as version 2 of the patch, and open up an editor for you to edit the message before you send it

Are you saying need to resend this particular patch? Should I just reply via Thunderbird/Mutt on any subsequent replies?

> Welcome to the kernel community. :)

Well, I only know Python well, but maybe I'll get into C someday soon :)

**Comment by mdeguzis** [comment]
oh ok, I see to resend the patch with V2.. ok. i'll resend

**Comment by ajdlinux** [comment]
By "commit title" I meant the first line of your commit message, which git send-email converts into the subject line of the email. Sorry if I was unclear! 

Yes, resend the patch after fixing up those issues. When you're sending a patch, use git send-email, but you can then use your normal email client for any discussion which happens in response.

**Comment by mdeguzis** [comment]
I removed extra space so I can do another git commit -s on this. However, if I was sending again, would I just use git-rebase to edit the commit?

I documented this previously in my documents repo:

**Comment by ajdlinux** [comment]
Yeah, use git rebase or git commit --amend to edit the commit.

**Pull request closed without merging**
