### PR TITLE
Merge origin repo updates

### PR DESCRIPTION
**Pull request by yuxuanchen1997**

### CODE REVIEW

**Comment by ak67** [comment]
YOU DUMBASS BITCH!!! TROVALDS DONOT ACCEPTS PULL REQUESTS HERE !!!!

**Comment by yuxuanchen1997** [comment]
I am sorry. I clicked pull request by mistake.

**Comment by Jheengut** [comment]
On Monday, January 19, 2015 02:03:55 AM Anubhav wrote:
> YOU DUMBASS BITCH!!! TROVALDS DONOT ACCEPTS PULL REQUESTS HERE !!!!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/torvalds/linux/pull/157#issuecomment-70469786
This is a bit brutal, but considering what's happenning lately 
	Yuxuan Chen should take it lightly

stiill Anubhav if linus does not ACCEPTS PULL REQUESTS , so what is the 
use of linux on github and secondly can't we disable the pull request

**Comment by yuxuanchen1997** [comment]
I am really sorry. I was about to fetch update from origin repositories yesterday and mistakenly pulled it to original repo and didn't even noticed.

#Really sorry about this.#

**Pull request closed without merging**
