### PR TITLE
this code a lot whole better and verry faster

### PR DESCRIPTION
**Pull request by SudoLinux**
It so fast now can run vinux on my shoess, should try put it good, and I got A+++++ on my project in school cuz this very fastly

### CODE REVIEW

**Comment by arnavb** [comment]
I only see a 1098 minuses on the left column of the files changed.

**Comment by VentGrey** [comment]
I barely comment here but shitposting has been increasing lately. Where did the good users went?

**Comment by dschwartz783** [comment]
@VentGrey Because people like to mimmic people who they see as having done something immensely popular, such as posting the original "very fast" PR. That PR generated a ridiculous number of comments, and so some people, such as @SudoLinux, have seen fit to mimmic that PR, in some attempt at gaining some sort of social brownie points, with which they can gain popularity. It never works well, but everyone tries it at some point, and sometimes you get a brownie point or two. Although, being the second person to mimmic this probably isn't going to do much.

**Comment by SudoLinux** [comment]
wow

**Comment by arnavb** [comment]
\*Mind Blown*

**Comment by VentGrey** [comment]
@dschwartz783 second places never get anything important, tho I don't know why there is so much "AW autism"

**Comment by SudoLinux** [comment]
Why are people even here, there are no "good people", Linus himself hates pull requests so he ignores them, its now basically a free sandbox of posts...

**Comment by tuxutku** [comment]
There are pulled requests, so you just better get banned @SudoLinux.

**Comment by tuxutku** [comment]
By the way is it torvalds himself opened this repository?

**Comment by sfxworks** [comment]
Work of art.

**Comment by xCuri0** [comment]
@tuxutku GitHub doesn't ban ?
Anyways whats with all these shitposts (or shitpulls) coming up recently ?

**Comment by cvilleger** [comment]
Very nice !

**Comment by SudoLinux** [comment]
Death

**Pull request closed without merging**
