### PR TITLE
Delete duplicate word "long long" in Introduction

### PR DESCRIPTION
**Pull request by AlonsoIbarra**
Hi friend, I delete a duplicate word.

### CODE REVIEW

**Comment by Antidote** [comment]
That's intentional.

**Comment by nistath** [comment]
It's not duplicate. long long is a type.

**Comment by battlesnake** [comment]
haha I see another reason why Linus might not take PRs from Github!

**Comment by Hugne** [comment]
https://www.youtube.com/watch?v=uc2UEfWjvo8

**Comment by jesusjimsa** [comment]
It's a data type...

**Comment by NogradThGin** [comment]
Dude your request if funny, but as said before "long long" is a data type.
And asking for changing a documentation for just one or two words is useless.

You can change some little details in documentation alongside interesting change in source code.

**Comment by xavier-fernandez** [comment]
It would be better to mark the `long long` keyword, so its more clear that the duplication its intentional and its actually a source code mention.

A good PR would be marking all the README.md data types and keywords...

**Comment by xavier-fernandez** [comment]
@battlesnake  If you humiliate somebody just starting to contribute, that person will not probably contribute again, you should teach them how to contribute, not humiliate them, open-source community should not tolerate this type of comments.

**Comment by jnavila** [comment]
The Linux kernel is a complex project, and you can not simply throw Github PRs at it.

Please read:
 * #25 
 * https://github.com/torvalds/linux/blob/master/Documentation/HOWTO
 * https://github.com/torvalds/linux/blob/master/Documentation/SubmittingPatches

**Comment by xavier-fernandez** [comment]
@jnavila This is a much better approach to this type of situation than the counterpart. 👍

**Comment by battlesnake** [comment]
@xavier-fernandez : meh, https://lkml.org/lkml/2012/7/6/495

**Comment by xavier-fernandez** [comment]
@battlesnake What you are trying to proof with this?

**Comment by battlesnake** [comment]
I was remarking on how you interpreted my remark on the (observably low) quality of issues/PRs on Github as me "humiliating" someone - when there is actual abusive/humiliating stuff in the kernel mailing list.

As for "teach them how to contribute" - there are much better resources available for learning to program in C than could be fit into Github comments.

"open-source community should not tolerate this type of comments" - because your opinion of how people should behave is gospel?  I'd point you to http://marc.info/?l=linux-kernel&m=137392506516022&w=2

Quit playing SJW or I may have to actually start humiliating...

**Comment by Antidote** [comment]
@xavier-fernandez no, why should linux developers dirty up the readme with frivolous nonsense that _most_ programmers would already know? And nobody on this PR has insulted anybody, you'd have to be pretty obtuse to think so.

**Comment by DTFUHF** [comment]
For this change to be better / more correct, shouldn't both 'longs' be removed?

**Comment by udemiko** [comment]
GitHub has nothing to do with this - people can still do big damage via email

**Comment by markand** [comment]
Best pull request I've ever seen in my life.

**Comment by janvdl** [comment]
@xavier-fernandez This is not a "safe space". This PR is absolutely laughable and idiotic.

**Comment by tonychee7000** [comment]
Hey guy,

Don't you know what are you doing?

**Comment by alucard0134** [comment]
those github community guidelines make it hard for me to not ridicule this guy but holy mother of god

**Comment by mimiatmam** [comment]
Omg why

**Comment by subzeta** [comment]
So long long Marianne. Best PR I've ever seen.

**Comment by alucard0134** [comment]
RIP

**Comment by cristianfrasineanu** [comment]
Was eager to see Linus' reaction to this...

**Comment by alucard0134** [comment]
one can hope still yet

**Comment by battlesnake** [comment]
Indeed

**Comment by camnpr** [comment]
Who are from the beginning of the rookie

**Comment by GinRyan** [comment]
I have a variable named `long long ago`, would you still remove the duplicatie word?

**Comment by mayli** [comment]
Is this a joke?

**Comment by gyb997** [comment]
haha what a funny joke

**Comment by ABcDexter** [comment]
Please don't try this at home!!
That second '!' was intentional, don't delete it.

**Comment by Yurunsoft** [comment]
硬吹丝挺

**Comment by SuperSuperSuperSuper5** [comment]
@Yurunsoft 评论就服你

**Comment by shitenglish** [comment]
说出来干什么，你以为我会同情你？我差点笑出声...

**Comment by mssd** [comment]
lol

**Comment by dilfish** [comment]
这周就靠这个 pr 保持心情了。

**Comment by alexkutsan** [comment]
Ну а что, Нормальное изменение, зачем слова дублировать?

**Comment by battlesnake** [comment]
"Found another typo in the source"

    - int block = 42;
    + in block = 42;

</s>

**Comment by kangkona** [comment]
Huoqianliuming

**Comment by CyberTailor** [comment]
It's so fat. LOL.

**Comment by andrshevch** [comment]
LMAO so hard

**Comment by THE-Swank** [comment]
Lol best PR

**Comment by marctmiller** [comment]
is op a mexican intellectual?

**Comment by marctmiller** [comment]
holy fucking shit this stupid ass thread stfu

next time a 'long long' comes along kindly close the fucking pr

wtunholyf

**Comment by K6F** [comment]
@shitenglish 你内涵了

**Comment by mrxf** [comment]
Nice work

**Comment by softarn** [comment]
As a non C programmer I could probably have done this mistake as well. It is a funny mistake though, but not stupid or idiotic.

**Comment by saidganim** [comment]
I hope , that it's a fat joke, otherwise it's sad =)

**Comment by evildog1** [comment]
it makes me laugh

**Comment by Fonger** [comment]
You're cute

**Comment by xialf** [comment]
it is a sad story....?

???? iPhone

? 2016?11?30????6:45?Fonger <notifications@github.com<mailto:notifications@github.com>> ???


You're cute

-

**Comment by berkantaydin** [comment]
I think, that guy, after that reactions; exited from community, software development and everything having microprocessor. I guess, leaving now from life too.

https://www.youtube.com/watch?v=hfHS7WCPc24

**Comment by XPompeii** [comment]
太屌了，Github能這樣玩，我也是暈了。

**Comment by aCoder2013** [comment]
what a funny guy

**Comment by lisper-inmove** [comment]
good job!

**Comment by neilhhw** [comment]
Gooood!

**Comment by gyc1299339354** [comment]
愿天堂没有long long

**Comment by qijianbo010** [comment]
u r cute.

**Comment by fcbruce** [comment]
It cured my tooth ache. 233333

**Comment by mingjunyang** [comment]
long long time ago, A very old programming language called C language.

**Comment by hello2t** [comment]
蛤。

**Comment by brycepg** [comment]
In a galaxy a long long away

**Comment by ThomasWFan** [comment]
可以。。这很Gayhub。。

**Comment by adyliu** [comment]
long long laugh

**Comment by PommyGit** [comment]
Took me a long long time to read this long long PR.

**Comment by battlesnake** [comment]
Was that a long double?

**Comment by xiaoxubeii** [comment]
Best PR and good work :|

**Comment by william-linchen** [comment]
linux tiro

**Comment by vpiotr** [comment]
It's a funny joke or a PR from newbie, calling this idiotic is too much for me.

Remember this joke?
`long long ago; /* in a galaxy far far away */`

**Comment by safdar-tp** [comment]
The above comment just reminded me star wars :'(

**Comment by oucaijun** [comment]
haha


oucaijun.happy@163.com
 
From: 李大虾
Date: 2016-11-29 19:43
To: torvalds/linux
Subject: Re: [torvalds/linux] Delete duplicate word "long long" in Introduction (#335)
说出来干什么，你以为我会同情你？我差点笑出声...

**Comment by lidanyang** [comment]
你仿佛在刻意逗我笑

**Comment by jason19659** [comment]
66666666

**Comment by dpych** [comment]
oh my god .., XD

**Comment by Gubio** [comment]
Nice job brother

**Comment by jwang-net** [comment]
LMAO

**Comment by LasseRafn** [comment]
I'd have done the same :) Honestly

**Comment by gocreating** [comment]
卡位朝聖

**Comment by GryPLOfficial** [comment]
He's a genius. How did we not see this?

**Comment by srikanth-vm** [comment]
lol.

**Comment by SadError256** [comment]
e

**Comment by prathik** [comment]
> haha I see another reason why Linus might not take PRs from Github!

You are right but it is better to be constructive. It is easy to say `you suck` and run away. This is rarely useful and only contributes to boost your ego.

It is better to clearly articulate what is wrong and then give the other person pointers on how they can improve.

The confusion happened because the committer is new to programming and for those who are new I see how it can look like a mistake. The keywords need to me marked with back ticks so that it is clear it is intentional.

Another thing that can be done is to quickly close the PR and ask them to do proper homework before raising a PR. But I understand you don't have the power to do the latter.

Also, don't rely on Linus as a role model of how to behave, he is only able to contribute because he is a good coder, however he is not a good coder because he is an asshole.

**Comment by gordio** [comment]
@prathik my asm code `mine bitcoin coins; mv coins my_wallet`; don't work. Can you, please, write "article comment" to describe how asm work and how I can use it? Thank you.

**Comment by terorie** [comment]
@gordio sir bitcoin is the hacker money please stop

**Comment by Veetaha** [comment]
Bruh

**Comment by plazmonii** [comment]
есе

**Comment by dincho** [comment]
I’m just passing by ... with my B1lla bag  🛒 🚶

**Comment by rollmind** [comment]
https://www.youtube.com/watch?v=lIueevl71cA

**Comment by strasharo** [comment]
https://www.youtube.com/watch?v=7t9JUns-Ql0

**Comment by yonifra** [comment]
Approved ✅

**Comment by IngridPuppet** [comment]
This will never get old 😂

**Comment by gordio** [comment]
Hi everyone. I believe it’s an opportune time to revisit this fix. xD

**Pull request closed without merging**
